### ISSUE TITLE
Why always crash from alpha14 (included alpha15) on Android 10, but the previous version will not have this problem.

### ISSUE THREAD

**Issue by jiashooter** [trojan-gfw/igniter#100]
Why always crash from alpha14 (included alpha15) on Android 10 with MIUI11, but the previous version will not have this problem, and how to capture the log from App?

**Comment by jiashooter** [comment]
I don't know how to collect log from the cellphone with app or maybe you can tell me methods. thx

**Comment by wongsyrone** [comment]
Please try commit: https://github.com/trojan-gfw/igniter/commit/7aaa1d045714576df746e455f5c487a3ee428327
