### ISSUE TITLE
Please support “multiple trojan server”

### ISSUE THREAD

**Issue by lancehzzz1202** [trojan-gfw/igniter#103]
Thanks for developing trojan，providing a fast and secure method to bypass the GFW.  I have given up on v2ray in favor of trojan.
During my use, I encountered an inconvenience. I have 2 virtual private servers, and I have installed Trojan on them. When I want to use trojan service over the other vps, I have to re-input the server's information.  If I could just switch the server nodes like v2rayN or ShadowSocks, it woud be more comfortable and efficient.

Best regards.

**Comment by oasiscifr** [comment]
https://github.com/trojan-gfw/igniter/issues/77
