### ISSUE TITLE
Speed slow down

### ISSUE THREAD

**Issue by yzzfzd** [trojan-gfw/igniter#104]
从 pre-alpha11开始, 你把libn2t换成tun2socks后，速度就变慢了。
用pre-alpha 10，我500M的宽带是可以跑满带宽的，从pre-alpha 11开始的版本，都跑不过50Mb/s。

**Comment by wongsyrone** [comment]
Please test this apk signed by my keystore: https://drive.google.com/open?id=1MjVwJNNbZa-gNYFEwaHRJXnLzOTwPdAd

**Comment by yzzfzd** [comment]
> Please test this apk signed by my keystore: https://drive.google.com/open?id=1MjVwJNNbZa-gNYFEwaHRJXnLzOTwPdAd

Thanks Syrone, It is better than alpha 15, but still slower than alpha 10, I have known what happened. thanks for your hard work.
