### ISSUE TITLE
redmi k20 miui11 20.3.5 didn't use

### ISSUE THREAD

**Issue by lululuqyw** [trojan-gfw/igniter#110]
redmi k20 Update 20.3.5，Wifi doesn't work properly after connection? However, it is NORMAL to use mobile data. I didn't find this problem in the Xiaomi Note2 test。
连接之后wifi无法正常使用？但是使用移动数据正常。我在小米 note2测试并未发现这种问题

**Comment by wongsyrone** [comment]
Close due to no logcat provided.

**Comment by llcat** [comment]
> Close due to no logcat provided.

@wongsyrone  hi, i have the same problem in redmi k20 pro, miui 11.0.5, when i switch to wifi, it can't use or very slower then pc(use trojan qt-5) connet the same ap,  where can i find the logcat file im my phone?

**Comment by llcat** [comment]
> > Close due to no logcat provided.
> 
> @wongsyrone hi, i have the same problem in redmi k20 pro, miui 11.0.5, when i switch to wifi, it can't use or very slower then pc(use trojan qt-5) connet the same ap, use lte network is ok, where can i find the logcat file in my phone?

ok, i find solution in other issue, #72 , because of the miui control back app's network, thanks
