### ISSUE TITLE
Refine the rules of clash (bypass mode)

### ISSUE THREAD

**Issue by oasiscifr** [trojan-gfw/igniter#118]
https://github.com/trojan-gfw/igniter/blob/master/app/src/main/res/raw/clash_config.yaml#L52

The domain rules here haven't been refined for a long time. If you find some APPs / Websites are wrongly directed to proxy during using bypass mode, pls report them here.

- app server domain
- app package name
- app name

**Comment by Piggy-Chu** [comment]
Hi, I'm here to report that Facebook and Instagram apps on Android are not being redirected correctly to the proxy. I am suspecting that the CDN domains of Facebook's services are not included in the proxy list. Thanks!

**Comment by philosopher233** [comment]
感觉speedtest.net可以加入Proxy, 方便测速。vultr.com一直DIRECT似乎没什么问题。

**Comment by wongsyrone** [comment]
Merge into https://github.com/trojan-gfw/igniter/issues/114
