### ISSUE TITLE
这版在stop的时候容易崩溃

### ISSUE THREAD

**Issue by heham** [trojan-gfw/igniter#119]
使用的时候还好，就是在stop的时候大概率发生卡死崩溃。

**Comment by heham** [comment]
补充，尤其是在网络连接质量不佳的情况下，比如数据网络信号不好或者WIFI有点卡的时候，卡死概率很大。

**Comment by xhrm** [comment]
Samsung S10+ Android 10 As exist

**Comment by oasiscifr** [comment]
dup: https://github.com/trojan-gfw/igniter/issues/117

**Comment by wongsyrone** [comment]
https://github.com/trojan-gfw/igniter/releases/tag/v0.1.0-pre-alpha17

**Comment by heham** [comment]
> https://github.com/trojan-gfw/igniter/releases/tag/v0.1.0-pre-alpha17

谢谢，我马上下载来看看。
