### ISSUE TITLE
建议增加以下功能

### ISSUE THREAD

**Issue by luobizheng** [trojan-gfw/igniter#120]
1.可导入和PC通用的config.json配置文件，可以多节点导入
2.增加手动节点选择以及网络链接质量测试按钮
3.多节点可以手动选择或者自动选择速度最优的节点链接
具体形式可参考shadowsocks的安卓版本--https://github.com/shadowsocks/shadowsocks-android
以上仅供参考。辛苦了

**Comment by tirabbit** [comment]
this is a very useful feature ,hope to fixed quickly👍

**Comment by RtYkk** [comment]
不开新的了就在本条下面补充吧。能有shortcut快捷开关，参考v2rayng和shadowsocks-Android

**Comment by maboloshi** [comment]
> 不开新的了就在本条下面补充吧。能有shortcut快捷开关，参考v2rayng和shadowsocks-Android

已经有人开了#59

**Comment by honthion** [comment]
pexil 2 手机5.0英寸不能一屏显示完，可以适配一下。tks

**Comment by RtYkk** [comment]
> pexil 2 手机5.0英寸不能一屏显示完，可以适配一下。tks

您说的是pixel 2吗？我用的是OG Pixel，Android版本QP1A.191005.007.A3也就是我能更新到的最新的Android 10，没有办法复现啊？能不能上个截图

**Comment by honthion** [comment]
是pixel 2，Android 10版本号 QQ2A.200305.002
当设置-显示-字体大小、显示大小都设置为小的时候一屏能显示完，如果是默认设置就会出现下图的现象。
![2](https://user-images.githubusercontent.com/22056897/77737664-63f2c700-7049-11ea-8a6a-a909ff47b2c5.png)

**Comment by RtYkk** [comment]
> > > pexil 2 手机5.0英寸不能一屏显示完，可以适配一下。tks
> > 
> > 
> > 您说的是pixel 2吗？我用的是OG Pixel，Android版本QP1A.191005.007.A3也就是我能更新到的最新的Android 10，没有办法复现啊？能不能上个截图
> 
> 是pixel 2，Android 10版本号 QQ2A.200305.002
> 当设置-显示-字体大小、显示大小都设置为小的时候一屏能显示完，如果是默认设置就会出现下图的现象。
> ![2](https://user-images.githubusercontent.com/22056897/77737664-63f2c700-7049-11ea-8a6a-a909ff47b2c5.png)

感觉可以复现，但是你手势该换了（

**Comment by luoxiao-xy** [comment]
同样，很需要这些功能：
1、PC通用的config导入
2、全部节点测速
3、多节点选择或者自动切换
4、快捷工具栏图标

**Comment by crifan** [comment]
同上，最希望加的：

- [ ]  全部节点测速 + 测速后排序（由快到慢）

否则节点多时（几十个），根本不知道哪个可用，使用效率非常低 😭

**Comment by wongsyrone** [comment]
@crifan  The feature you mentioned has been added from 0.10.0-beta

**Comment by crifan** [comment]
@wongsyrone thanks for you quick reply.
BTW: minutes ago, has found :

> Add support to test all proxy servers' ping delay.

in [igniter 0.10.0-beta Changelog](https://github.com/trojan-gfw/igniter/releases)

and is downloading and try to verify it. now indeed supported:

![WechatIMG755](https://user-images.githubusercontent.com/2750682/98495904-3165a980-227b-11eb-85cf-bcf7515e8ad8.jpeg)


Thanks. 👍
