### ISSUE TITLE
Trojan Slow response time

### ISSUE THREAD

**Issue by kongbai39** [trojan-gfw/igniter#122]
When I use Trojan on some phones, the response time of Trojan is very slow.

EXAMPLE:
It takes a long time to start playing with Youtube, but the network speed is normal. I need a minute or more to load to play, and the network connection speed is 0.

With the same configuration, IOS and PC are not affected, and only some android phones are affected

**Comment by Malcolm-Allen** [comment]
agreed

**Comment by LimiQS** [comment]
If you are using Igniter, please open an issue there. If you are using other Android client, please consult corresponding project maintainers.
