### ISSUE TITLE
Igniter's speed  is  slower than windows client on PC

### ISSUE THREAD

**Issue by kireiyume** [trojan-gfw/igniter#124]
In the same network(5Ghz wifi),windows client can watching  8K 60FPS  videos,The Igniter's  maximum speed just  10mbps.The device is Mi8UD, android 10

`{
    "run_type": "client",
    "local_addr": "127.0.0.1",
    "local_port": 1080,
    "remote_addr": "xxx.xxx",
    "remote_port": 443,
    "password": [
        "qwer1234"
    ],
    "log_level": 1,
    "ssl": {
        "verify": true,
        "verify_hostname": true,
        "cert": "fullchain.cer",
        "cipher_tls13":"TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
"sni": "",
        "alpn": [
            "h2",
            "http/1.1"
        ],
        "reuse_session": true,
        "session_ticket": false,
        "curves": ""
    },
    "tcp": {
        "no_delay": true,
        "keep_alive": true,
        "fast_open": false,
        "fast_open_qlen": 20
    }
}`

**Comment by oasiscifr** [comment]
It doesn't make sense to compare speeds on different devices.
