### ISSUE TITLE
app dosent work in wifi mode

### ISSUE THREAD

**Issue by sadraese** [trojan-gfw/igniter#127]
hello everyone , i setup a server
client on windows and mac working fine with wifi 
but on android when i connect to wifi the connection is not established 
only when i use 4G and 3G data it will be ok .

**Comment by liuxaz** [comment]
xiaomi？

**Comment by liuxaz** [comment]
xiaomi？

**Comment by sadraese** [comment]
no it huawei P10

**Comment by heham** [comment]
我的也是华为无线和数据都可以

**Comment by sadraese** [comment]
anyway to debug what is the problem ?
