### ISSUE TITLE
A18仍然不稳定

### ISSUE THREAD

**Issue by Vendman** [trojan-gfw/igniter#131]
A18虽然解决了锁死的问题，但又有了新问题：会自动断开连接。已经在手机设置里允许了后台运行，但手机放那不用，过一段时间(没记录具体时长，估计个把小时)再打开，发现Igniter已经断开连接了（手机顶部状态栏的小钥匙图标消失），要到APP里重新按START恢复连接。

**Comment by GreaterFire** [comment]
@Vendman It might be problems related to Trojan. Hold on. Looking into it.

**Comment by findlayfeng** [comment]
我也遇到这样的问题

**Comment by DavidChou92** [comment]
我也遇到这个问题了。。

**Comment by findlayfeng** [comment]
服务器更新1.5.1后没有改善

**Comment by wongsyrone** [comment]
Please try https://github.com/trojan-gfw/igniter/releases/tag/v0.1.0-pre-alpha19

**Comment by Ltre** [comment]
同样遇到断流的问题

**Comment by wongsyrone** [comment]
> 同样遇到断流的问题

哪个版本？是否遵循升级提示

**Comment by findlayfeng** [comment]
> Please try https://github.com/trojan-gfw/igniter/releases/tag/v0.1.0-pre-alpha19

19版刚刚也断了
我下的是debug版本，可以导出日志吗？我看不到日志

**Comment by Anondot** [comment]
目前用的版本19，我的问题是连接节点后的最初十几秒速度非常快，然后就明显衰减了，这时再测试节点延迟，从最初几十毫秒变成了几千毫秒。然后断开节点连接，重连，速度又恢复了，过了一会儿速度又衰减了，不知道是不是所谓的断流，谢谢你的开发

**Comment by findlayfeng** [comment]
问题解决了？

**Comment by wongsyrone** [comment]
是的，只要遵循版本发布页的升级提示
