### ISSUE TITLE
 pixel 2 手机5.0英寸不能一屏显示完，可以适配一下。tks

### ISSUE THREAD

**Issue by honthion** [trojan-gfw/igniter#134]
> > > pexil 2 手机5.0英寸不能一屏显示完，可以适配一下。tks
> > 
> > 
> > 您说的是pixel 2吗？我用的是OG Pixel，Android版本QP1A.191005.007.A3也就是我能更新到的最新的Android 10，没有办法复现啊？能不能上个截图
> 
> 是pixel 2，Android 10版本号 QQ2A.200305.002
> 当设置-显示-字体大小、显示大小都设置为小的时候一屏能显示完，如果是默认设置就会出现下图的现象。
> 

感觉可以复现，但是你手势该换了

_Originally posted by @RtYkk in https://github.com/trojan-gfw/igniter/issues/120#issuecomment-604938857_

**Comment by wongsyrone** [comment]
No such device.
