### ISSUE TITLE
igniter cannot connect to google play store !!! Ignite没法连接到google play商店！！！

### ISSUE THREAD

**Issue by teaRRe** [trojan-gfw/igniter#136]
设备：三星S10
提示：从服务器检索信息时出错。DF-DFERH-01
这个现象出现在重置手机之后，试过很多种方法，最后换成其他VPN才解决。

Device: Samsung S10
Tip: An error occurred while retrieving information from the server. DF-DFERH-01
This phenomenon occurs after resetting the phone. I tried many methods, and finally changed to another VPN to solve.

**Comment by xhrm** [comment]
设置~应用管理~找到谷歌服务 ~清除数据，就可以了

**Comment by xiongmaoshouzha** [comment]
我的s8也不行，浏览器可以访问

**Comment by xiongmaoshouzha** [comment]
> 我的s8也不行，浏览器可以访问

发现解决办法了，网上说是谷歌商店会访问services.googleapis.cn，把Bypass China with clash 去掉勾选全部走代理就可以了

**Comment by isu122** [comment]
我这里的问题是，a19版本，bypass china选项关闭、exempt apps列表里一个app都不打开，还是不能访问任何谷歌系app，商店、gmail、地球、地图都不行，但是浏览器可以正常访问外网。

**Comment by isu122** [comment]
我的问题是A19版本连google系应用程序不太稳定，关闭bypass选项，exempt app里啥都不选，也是有一定几率连不上google系应用，商店、gmail、地球、地图这些都不行，但是浏览器直接访问没问题。

**Comment by ibitr** [comment]
同上，google系APP经常连不上或很慢，但用浏览器直接访问没问题。

**Comment by cuifua** [comment]
我也是！！！所有方法都试过了！！

**Comment by accwill** [comment]
同上

**Comment by teaRRe** [comment]
> 设置~应用管理~找到谷歌服务 ~清除数据，就可以了

我试过，还真不行..........

最新解决办法：服务器重装一遍trojan.............
不过有连接play商店等软件的通病：缓冲10秒...
截至目前，商店游戏界面下的“为您推荐”还是刷新不出来，其他正常

**Comment by cuifua** [comment]
重新安装就好了

**Comment by wongsyrone** [comment]
https://github.com/trojan-gfw/igniter/issues/150#issuecomment-609039037
