### ISSUE TITLE
A19版本问题

### ISSUE THREAD

**Issue by Nofear1003** [trojan-gfw/igniter#137]
国内网络大流量下载时会造成掉线，今天用百度地图下载离线数据，链接后准备看FB，但是瞬间掉线。重复几次都是瞬间掉线。

**Comment by DavidChou92** [comment]
我也遇到了类似的问题，但不是在下载时出现。
表现为：手机网络突然变差（国内网络完全连接不到，微信微博等都无网络；国外连接速度非常慢），将igniter连接断开后，国内网络恢复通畅。需要等待30秒左右才能再次连接igniter。

**Comment by Nofear1003** [comment]
刚才用YouTube又掉线了

**Comment by aryMBLec** [comment]
表示也有这个问题，排除掉国内应用可以解决，估计是分流规则有问题。

**Comment by Nofear1003** [comment]
有可能吧，遇到大流量下载会出问题。因为后来我用youtube也遇到过几次掉线。

**Comment by lpn418** [comment]
确实有这个问题，看YouTube软件崩了，安卓10

**Comment by Nofear1003** [comment]
logcat文件名是什么，默认储存在哪里？
