### ISSUE TITLE
socks5代理端口每次都随机，无法固定导致Telegram每次上网，都要重设代理端口

### ISSUE THREAD

**Issue by cdwangtao** [trojan-gfw/igniter#144]

**Comment by GreaterFire** [comment]
@cdwangtao Please set the local_port field in your config file to a non-zero value.

**Comment by GreaterFire** [comment]
@GreaterFire Ignore me.

**Comment by wongsyrone** [comment]
Works as expected.

**Comment by TchaikovDriver** [comment]
Disable the proxy settings in Telegram and do not exempt Telegram from Igniter.

**Comment by cdwangtao** [comment]
> Disable the proxy settings in Telegram and do not exempt Telegram from Igniter.

Alright. Thank you.
