### ISSUE TITLE
没有分流功能(像v2rayn一样:按ip、域名分流、分应用代理)，所有的app都走代理，导致国内的app上网很慢

### ISSUE THREAD

**Issue by cdwangtao** [trojan-gfw/igniter#145]
没有分流功能(像v2rayn一样:按ip、域名分流、分应用代理)，所有的app都走代理，导致国内的app上网很慢

**Comment by TchaikovDriver** [comment]
1. Enable 'Bypass China with Clash'.
2. Build your own app-bypass list in 'Exempt App' (Find it in options menu)

**Comment by wongsyrone** [comment]
Use the latest release and explore it by yourself.
