### ISSUE TITLE
alpha19版本问题

### ISSUE THREAD

**Issue by Dewcat** [trojan-gfw/igniter#147]
华为emui 8.0.0 安卓版本8.0.0 已根据正确的安装方式卸载重启并安装
连接至任何的节点均无法连接至google 这些节点在PC版的trojan上均可以正常使用
logcat:
https://paste.ubuntu.com/p/NNmkvF4WpV/

**Comment by TchaikovDriver** [comment]
Didn't find any useful log. You said that you cannot connect google. Which one do you mean? Cannot browse google.com or have a difficulty using google apps?

**Comment by Dewcat** [comment]
> Didn't find any useful log. You said that you cannot connect google. Which one do you mean? Cannot browse google.com or have a difficulty using google apps?

是指在使用app内置的''Test connection''时显示''Failed connect to google.com''同时一切被gfw限制的网站均无法访问
如果寻找不到问题那可能是我的设备原因 感谢帮忙寻找 辛苦了

**Comment by TchaikovDriver** [comment]
> > Didn't find any useful log. You said that you cannot connect google. Which one do you mean? Cannot browse google.com or have a difficulty using google apps?
> 
> 是指在使用app内置的''Test connection''时显示''Failed connect to google.com''同时一切被gfw限制的网站均无法访问
> 如果寻找不到问题那可能是我的设备原因 感谢帮忙寻找 辛苦了

Well I encountered this problem several times :) 
Try to test the connection a few seconds after the connection is established. If it doesn't work, pray that the bug would be resolved soon XD

**Comment by wongsyrone** [comment]
Cannot reproduce, if you can provide more info or log, please reopen it.
