### ISSUE TITLE
alpha20一样不能打开谷歌系APP，但网页访问正常。

### ISSUE THREAD

**Issue by ibitr** [trojan-gfw/igniter#150]
alpha20一样不能打开谷歌系APP，但网页访问正常。
跟https://github.com/coolsnowwolf/lede/issues/2684出现的一样，请大神参考看看。

**Comment by Ltre** [comment]
我也发现了

不过是打开谷歌系如google和youtube容易断开连接

**Comment by fedoranhowl** [comment]
今天晚上也出现了这问题，软件关闭“绕过中国”全局后正常。
DNS缓存泄露，v2ray有这方面的方案。

**Comment by wongsyrone** [comment]
1. The user who has root access, please edit clash config directly
2. Wait for https://github.com/trojan-gfw/igniter/issues/114.
3. I will add `googleapis.cn` to clash rule in the future, not guaranteed.

**Comment by wongsyrone** [comment]
Should be fixed via https://github.com/trojan-gfw/igniter/commit/fc15948b340fc7015ea5c10f2f2d49919118424f

**Comment by noobww** [comment]
> Should be fixed via [fc15948](https://github.com/trojan-gfw/igniter/commit/fc15948b340fc7015ea5c10f2f2d49919118424f)

did it and solved the problem, but now play store cannot be accessed thru app again. The .yaml is the replaced one, which once solved the problem.

**Comment by wongsyrone** [comment]
Simply replace the file or apply changes won't work, please follow instructions in the release page.

ref: https://github.com/trojan-gfw/igniter/releases/tag/v0.1.0-pre-alpha21
