### ISSUE TITLE
Please sort apps by name instead of package name

### ISSUE THREAD

**Issue by noobww** [trojan-gfw/igniter#152]
- or exempted list backup-restore feature.

really hard to look for a certain app for the first time, as well as doing it all over again after suggested "uninstall-reboot-install" update steps for such a frequently updated (much appreciated though) app!

**Comment by wongsyrone** [comment]
Open PR

**Comment by TchaikovDriver** [comment]
> * or exempted list backup-restore feature.
> 
> really hard to look for a certain app for the first time, as well as doing it all over again after suggested "uninstall-reboot-install" update steps for such a frequently updated (much appreciated though) app!

Reasonable, I will do that lately.

**Comment by zhangzhhz** [comment]
> > * or exempted list backup-restore feature.
> > 
> > really hard to look for a certain app for the first time, as well as doing it all over again after suggested "uninstall-reboot-install" update steps for such a frequently updated (much appreciated though) app!
> 
> Reasonable, I will do that lately.

Maybe also to add a search bar.
