### ISSUE TITLE
恳请极简客户端

### ISSUE THREAD

**Issue by fedoranhowl** [trojan-gfw/igniter#154]
作者你好，冒昧请求包装一个简单一点的版本，不包含clash最好，理由如下：
  “save”与“stop”在我的手机上只能看到save,况且也不是经常“save”,抱歉屏幕小。
  “Bypass China”总有不全的列表，我也不认为作者有义务尽善尽美，如果需要访问中文站关掉代理软件就好了。
  分享链接更有利于机场用户，测试项……这个不说。
我就想要一个原始界面的极简版本，内核最新就行，不需要clash,不需要各种功能，甚至状态栏通知。可以吗？

**Comment by wongsyrone** [comment]
No such plan.
