### ISSUE TITLE
Igniter打开时会唤醒键盘

### ISSUE THREAD

**Issue by HungryWolfww** [trojan-gfw/igniter#156]
即使已经编辑过信息，之后每次打开依旧会唤醒键盘。一个向下兼容的小问题。
Android版本：8.1.0
![photo_2020-04-07_09-42-08](https://user-images.githubusercontent.com/63271812/78621088-4a0c7c00-78b4-11ea-9f40-ee4ce4a4189f.jpg)

**Comment by philosopher233** [comment]
Android 8.1
![igniter](https://user-images.githubusercontent.com/39409532/78622993-2e57a480-78b9-11ea-89a2-b49cccbe4358.gif)

**Comment by TchaikovDriver** [comment]
This is weird. Never see this on both of my phones. Would you mind providing information about your phone? Brand, model, ROM and Android version, etc.

**Comment by philosopher233** [comment]
> This is weird. Never see this on both of my phones. Would you mind providing information about your phone? Brand, model, ROM and Android version, etc.

这个是出现问题的手机:  
[红米4 高配版](https://forum.xda-developers.com/redmi-4-prime)  
[LineageOS 15.1](https://drive.google.com/drive/folders/1hGQoixLYwJZWNx0pcPVF-DlKi11Wb-_U)  
Android 8.1

而另一部手机没有问题:  
[红米K20 Pro 尊享版](https://forum.xda-developers.com/k20-pro)  
[Evolution X](https://sourceforge.net/projects/evolution-x/files/raphael/) 4.1.69  
Android 10

**Comment by TchaikovDriver** [comment]
> > This is weird. Never see this on both of my phones. Would you mind providing information about your phone? Brand, model, ROM and Android version, etc.
> 
> 这个是出现问题的手机:
> [红米4 高配版](https://forum.xda-developers.com/redmi-4-prime)
> [LineageOS 15.1](https://drive.google.com/drive/folders/1hGQoixLYwJZWNx0pcPVF-DlKi11Wb-_U)
> Android 8.1
> 
> 而另一部手机没有问题:
> [红米K20 Pro 尊享版](https://forum.xda-developers.com/k20-pro)
> [Evolution X](https://sourceforge.net/projects/evolution-x/files/raphael/) 4.1.69
> Android 10
> 
> 使用的键盘均为Gboard

Thanks, the problem will be solved in the next release.

**Comment by philosopher233** [comment]
Thank you!

**Comment by wongsyrone** [comment]
https://github.com/trojan-gfw/igniter/releases/tag/v0.1.0-pre-alpha21
