### ISSUE TITLE
Feature:bypass china domain/ip and local network

### ISSUE THREAD

**Issue by emiyalee1005** [trojan-gfw/igniter#17]
Sorry for my pool english first.

Could you provide an options to bypass china domain/ip, which should not be proxy by trojan server, especially for users who live in china. Otherwise, in most situation, it will just make big lag or 404 for these sites. 

Just like https://github.com/shadowsocks/shadowsocks-android

**Comment by LimiQS** [comment]
According to some anonymous internal source, this feature will not be implemented at least in the short term.

**Comment by GreaterFire** [comment]
Forgive my laziness. Maybe we need some enthusiastic developers to implement these functionalities.

**Comment by KunagisaYuki** [comment]
@GreaterFire I think add per-app proxy is much more easier since this feature is provided in Android's VPN machinism

**Comment by emiyalee1005** [comment]
Got it, anyway thank you for your great effort to this project
