### ISSUE TITLE
Persistent notification takes too much vertical space

### ISSUE THREAD

**Issue by oldherl** [trojan-gfw/igniter#177]
https://github.com/trojan-gfw/igniter/blob/75557b993a0e715535be1a5ca3bd51625a97d268/app/src/main/java/io/github/trojan_gfw/igniter/ProxyService.java#L386

The current notification takes too much space: 1 line of title and 4 lines of text!
It makes the screen too crowded and often I have to scroll down to see other messages.

Could we squeeze them into just one line, like "Igniter running on ports xx/xx/xx"?
Or (through an option), remove all those port numbers from the notification bar and only show them in the main Activity or in the log?

**Comment by oldherl** [comment]
And the trailing `"\n" ` is completely useless, and the extra newline is inconsistent with all other apps' notification.

**Comment by oasiscifr** [comment]
@oldherl Would be fixed before the first beta release.
