### ISSUE TITLE
Android Min Version

### ISSUE THREAD

**Issue by zhangweikang** [trojan-gfw/igniter#178]
my phone android version 4.4.2 installation failed"Parsing package failed",igniter android min version how many?

**Comment by TchaikovDriver** [comment]
The minimum sdk version of Igniter is 21, which means your phone's Android version should be 5.0 at lease.

**Comment by zhangweikang** [comment]
thanks,Can I try to modify the minimum supported version of the clone source code and package it myself? Or that there are functions in the source code that must rely on the new features of Android 5.0, even if the minimum version is specified, it does not make sense

**Comment by TchaikovDriver** [comment]
You can adapt the codes to lower Android version for personal usage. At lease, exempt app feature will not work in sdk version less than 21. This is an open-source project, feel free to build your own version.

**Comment by zhangweikang** [comment]
thanks

**Comment by loko2000** [comment]
Hey buddy, have you build your igniter for android 4.4?
