### ISSUE TITLE
Tiktok international not accessible with or without clash

### ISSUE THREAD

**Issue by hb4ch** [trojan-gfw/igniter#183]
Machine: Huawei P30 Pro EMUI 10.0.0
Trojan server version : 1.15
Igniter version: 0.1.0-pre-alpha21

Everything else works. Only tiktok doesn't work.

**Comment by oasiscifr** [comment]
@hb4ch Doesn't work without clash? You mean Works with clash?

**Comment by hb4ch** [comment]
@oasiscifr Sorry for the typo. I meant with or without.

**Comment by wongsyrone** [comment]
Tiktok international variant blocks Chinese SIM card.
