### ISSUE TITLE
Igniter often stop working, and the network speed is low.

### ISSUE THREAD

**Issue by iostreamx** [trojan-gfw/igniter#184]
[logcat.txt](https://github.com/trojan-gfw/igniter/files/4496044/logcat.txt)
![IMG_20200418_123523](https://user-images.githubusercontent.com/63491179/79628186-5bd20700-8171-11ea-9ad4-26c944064575.jpg)
![IMG_20200413_091622](https://user-images.githubusercontent.com/63491179/79628189-64c2d880-8171-11ea-9de6-34be45b24768.jpg)
![IMG_20200413_091543](https://user-images.githubusercontent.com/63491179/79628190-67bdc900-8171-11ea-8368-d04c103be8f0.jpg)

The network speed test time is the same.

**Comment by iostreamx** [comment]
And the server is the same, too.

**Comment by xbxbox** [comment]
速度这个问题我已经反馈过很多次了，从alpha 17的版本开始，速度最高只能60m左右

**Comment by iostreamx** [comment]
> 速度这个问题我已经反馈过很多次了，从alpha 17的版本开始，速度最高只能60m左右

But no one reply.

**Comment by wongsyrone** [comment]
Please test this apk: https://drive.google.com/open?id=1Q6epDPW2wZsGzknbIaajzyrgpkLwl3NS

**Comment by iostreamx** [comment]
![Screenshot_20200425-101559729~2](https://user-images.githubusercontent.com/63491179/80269311-39943800-86e1-11ea-848e-5c4f03c19de2.jpg)
![Screenshot_20200425-103650675~3](https://user-images.githubusercontent.com/63491179/80269314-3ef18280-86e1-11ea-972f-9c4aecfdf533.jpg)
![Screenshot_20200425-102835057 (1)](https://user-images.githubusercontent.com/63491179/80269319-4dd83500-86e1-11ea-9f9e-5ca5c6462e31.jpg)
@wongsyrone Sorry, it does not work.
Same server and same time.

**Comment by wongsyrone** [comment]
Please test these apks:

4MB-MEM: https://drive.google.com/open?id=1f35ohN0_9Qu9s2s7_ZPMV3khNaO7KoIT

16MB-MEM-orig: https://drive.google.com/open?id=1z7gD8v3pVGMG3vK7w82AYdNU8rGzWtz9

16MB-MEM-all-external-flag: https://drive.google.com/open?id=1C9kQG7wB4x42DRxZ5P3DeDVI5OVBo6kQ

**Comment by wongsyrone** [comment]
If everything looks OK, `16MB-MEM-all-external-flag` will be included in the next release.

**Comment by iostreamx** [comment]
Thanks a lot. I will have a try.

**Comment by iostreamx** [comment]
@wongsyrone 
![4MB_MEM_1](https://user-images.githubusercontent.com/63491179/80328755-d9cd9680-8872-11ea-9f9e-fc6cd8a86e85.jpg)
![4MB_MEM_2](https://user-images.githubusercontent.com/63491179/80328763-e18d3b00-8872-11ea-83f5-50990a8baf5a.jpg)
![16MB_MEM_all-external-flag_1](https://user-images.githubusercontent.com/63491179/80328764-e2be6800-8872-11ea-8a0a-03fff5eb742b.jpg)
![16MB_MEM_all-external-flag_2](https://user-images.githubusercontent.com/63491179/80328766-e3ef9500-8872-11ea-8611-09a8cf4eb84d.jpg)
Same server, same time.

`16MB-MEM-orig` version cannot connect to the Speedtest server, but it can connect to Google.

YouTube 4K video is about 25000Kbps. (Both versions)

`4MB-MEM` is faster than `16MB-MEM-all-external-flag`

I have tested each version at least 3 times.

**Comment by wongsyrone** [comment]
OK. Thanks for the feedback.

**Comment by iostreamx** [comment]
> OK. Thanks for the feedback.

You're welcome.

**Comment by wongsyrone** [comment]
@iostreamx 

Can you test this apk and make sure it works like `4MB-MEM`

https://drive.google.com/open?id=1NMI9_1P9cZigK8_-J-TT8QpAOql40HF7

**Comment by iostreamx** [comment]
@wongsyrone 
Yesterday my ISP was China Telecom, and today my ISP is China Mobile.
![Screenshot_20200428-112224095 (1)](https://user-images.githubusercontent.com/63491179/80444311-000f3700-8944-11ea-9868-bca47b491bfc.jpg)

**Comment by wongsyrone** [comment]
Thanks. It looks the issue has been fixed

**Comment by xbxbox** [comment]
新版的确快了很多！

**Comment by iostreamx** [comment]
> 新版的确快了很多！

Yup.
