### ISSUE TITLE
Exempting apps takes no effect?

### ISSUE THREAD

**Issue by noobww** [trojan-gfw/igniter#185]
slow loading domestic pages in exempted apps if igniter has started. by stopping it, loading gets light-fast

**Comment by TchaikovDriver** [comment]
You mean that you exempt your browser and then it loads domestic websites slowly?

**Comment by noobww** [comment]
> You mean that you exempt your browser and then it loads domestic websites slowly?

exempted CoolApk (a domestic community) app, and it loads all thread content slowly.

**Comment by TchaikovDriver** [comment]
I can't reproduce it on both of my phones. Have you updated Igniter to latest release? Also, make sure you save the exempt app list before using Igniter.
