### ISSUE TITLE
我手机上的v21版本还是无法正常使用google系app

### ISSUE THREAD

**Issue by isu122** [trojan-gfw/igniter#188]
如题，Exempt Apps列表里都关闭了，Bypass选项不管开关，都无法使用Google系app正常访问网络，手机浏览器可以正常访问。
另外，采取如下措施可以让igniter短时期支持Google系app访问：1、打开网络下载的免费vpn软件；2、打开Google系app，正常连接；3、关闭免费vpn和Google系app；4、打开igniter；5、再打开Google系app，则Google系app可以短期通过igniter访问，但长期待机后还是会无法访问。
求教！
手机是三星S8+，android版本9，未root。

**Comment by DavidChou92** [comment]
有点好奇你的Google是三星自带的，还是自己安装的框架？看到你提这个问题好多次了。

**Comment by isu122** [comment]
> 
> 
> 有点好奇你的Google是三星自带的，还是自己安装的框架？看到你提这个问题好多次了。

是手机自带的框架。

**Comment by archy8088** [comment]
我也是这个问题；
手机上的google store，youtube，无法使用
但是chrome浏览器访问良好。
是不是代理问题？

**Comment by isu122** [comment]
我换了v22版本，问题依旧，我装了个logcat reader看了下前后的日志，似乎问题出在“[GoogleAccountDataServiceImpl] getToken() -> NETWORK_ERROR. Account: <ELLIDED:-917963514>, App: com.android.vending, Service: oauth2:https://www.googleapis.com/auth/googleplay
ske: Error when calling server.”，这个网址应该是验证账号用的吧，那也能解释为什么我先用其他vpn联网以后短时间内可以让igniter支持google系app，因为验证已经通过了，不过过一段时间再验证的时候只用igniter又通不过，所以google系app就很快就又不能上了。

**Comment by ucssi-dongxd** [comment]
你好。能否留个联系方式请教下 185200639

**Comment by oasiscifr** [comment]
https://github.com/trojan-gfw/igniter/issues/197 check this and reopen if problem persists.

**Comment by Assiyvril** [comment]
我的三星note9也有这个问题，Android10。请问你解决了吗？

**Comment by TchaikovDriver** [comment]
> 我的三星note9也有这个问题，Android10。请问你解决了吗？

Try the debug apk [here](https://github.com/TchaikovDriver/igniter/releases/tag/0.9.5.1-beta)

**Comment by isu122** [comment]
我换了个软件暂时解决了。小水滴安卓版。

Frost <notifications@github.com> 于2020年5月30日周六 下午1:29写道：
