### ISSUE TITLE
A switch to shift including/exempting apps from VPN

### ISSUE THREAD

**Issue by oasiscifr** [trojan-gfw/igniter#189]
It would help to reduce the pain of choosing APPs those need to go through VPN.

It's possible to implement with this API:
[VpnService.Builder#addAllowedApplication](https://developer.android.com/reference/android/net/VpnService.Builder#addAllowedApplication(java.lang.String))

**Comment by TchaikovDriver** [comment]
Coming soon.

**Comment by TchaikovDriver** [comment]
#245
