### ISSUE TITLE
Feature: custom host support

### ISSUE THREAD

**Issue by emiyalee1005** [trojan-gfw/igniter#19]
In my region, the isp pollute the dns and my host often failed to resolve for 50% of the time. So a custom host feature will help me a lot. 
Currently on my PC, i can manually modify the host file but on my android phone without root, there is no way to modify host while running the trojan

**Comment by GreaterFire** [comment]
@emiyalee1005 You can try to enter the IP address in remote_addr and enter the domain name in the sni field. This is equivalent to entering the domain name in remote_addr except that trojan doesn't resolve the name anymore.

**Comment by emiyalee1005** [comment]
Yeah, will try this on windows client. But on android client igniter, i can't find this field

**Comment by KunagisaYuki** [comment]
@emiyalee1005 this is *designed* not working on Android client igniter. We suggest that you should use termux or something alike to run native binary and use a socks2vpn tools(you may find some in Google play)

**Comment by GreaterFire** [comment]
@emiyalee1005 Igniter is still in its pre-alpha stage. At this time, rich feature should not be expected.

**Comment by emiyalee1005** [comment]
Got it, will try the solution. But happy if the later version can support this feature.
