### ISSUE TITLE
connection closed by peer

### ISSUE THREAD

**Issue by zhedian** [trojan-gfw/igniter#194]
连接时提示connection closed by peer

**Comment by wongsyrone** [comment]
Post logcat, screenshot or screen recording.

**Comment by Shelling0** [comment]
![Screenshot_2020-04-27-13-07-02-095_io github troj](https://user-images.githubusercontent.com/9719980/80335911-4e5f0000-8888-11ea-95b5-00568dcbb4b0.png)

**Comment by zhedian** [comment]
![Screenshot_20200427_183759_io github trojan_gfw igniter](https://user-images.githubusercontent.com/21031846/80363572-fee3f880-88b6-11ea-9ec9-67236cc4cc33.jpg)
![Screenshot_20200427_183602_io github trojan_gfw igniter](https://user-images.githubusercontent.com/21031846/80363602-073c3380-88b7-11ea-885f-ec11c6a9c25e.jpg)

![Screenshot_20200427_184526_io github trojan_gfw igniter](https://user-images.githubusercontent.com/21031846/80363864-70bc4200-88b7-11ea-83a2-663b17df432d.jpg)

can't open logcat.

**Comment by iostreamx** [comment]
> ![Screenshot_20200427_183759_io github trojan_gfw igniter](https://user-images.githubusercontent.com/21031846/80363572-fee3f880-88b6-11ea-9ec9-67236cc4cc33.jpg)
> ![Screenshot_20200427_183602_io github trojan_gfw igniter](https://user-images.githubusercontent.com/21031846/80363602-073c3380-88b7-11ea-885f-ec11c6a9c25e.jpg)
> 
> ![Screenshot_20200427_184526_io github trojan_gfw igniter](https://user-images.githubusercontent.com/21031846/80363864-70bc4200-88b7-11ea-83a2-663b17df432d.jpg)
> 
> can't open logcat.

https://baike.baidu.com/item/Logcat/5028737?fr=aladdin
https://developer.android.google.cn/studio/command-line/logcat

**Comment by iostreamx** [comment]
If you are using an IP address instead of a domain, you should turn off `Verify Certificate`.

**Comment by oasiscifr** [comment]
https://github.com/trojan-gfw/igniter/issues/197 check this and reopen if problem persists.
