### ISSUE TITLE
Logs in my Android show SSL handshake failed

### ISSUE THREAD

**Issue by odorea** [trojan-gfw/igniter#20]
Thanks for your effort to make this impressive project and it surely work well on my machine. But I still have a question with the specific Android client.

I have tested my service on IOS(by shadowrocket) and windows. It is built in docker and uses CA certificate. While it runs well, my Android still can not connect to the server. There is no warning in my server log, while logs in my Android show:

 [ERROR] 127.0.0.1:59967 SSL handshake failed with *********:443: stream truncated

I've tried settings with or without certificate verification and the error still exists. I even input my certificate into Android and things didn't change.

What can I do to fix it? Or is there any formed solution cooperate with trojan? 

Thank you.

**Comment by odorea** [comment]
Another detail I found in Android logs is that the local port of the service changed all the time. I don't have an idea whether this is normal.
-----------------------------------------------------------------------
E/trojan  (15015): [2019-06-08 05:44:49] [ERROR] 127.0.0.1:35982 SSL handshake failed with ***:443: stream truncated

E/trojan  (15015): [2019-06-08 05:44:49] [ERROR] 127.0.0.1:35980 SSL handshake failed with **:443: stream truncated

E/trojan  (15015): [2019-06-08 05:44:49] [ERROR] 127.0.0.1:35978 SSL handshake failed with ***:443: stream truncated

**Comment by GreaterFire** [comment]
Stream truncated means the connection is closed by the other endpoint for some unknown reasons.

Changing port is totally normal.
