### ISSUE TITLE
too much battery use on miui10

### ISSUE THREAD

**Issue by auguscqy** [trojan-gfw/igniter#209]
too much battery use on miui10。
![Screenshot_2020-04-30-09-55-24-969_com miui securitycenter](https://user-images.githubusercontent.com/19179913/80664234-cfa4d580-8ac8-11ea-9103-39e3d2e83ac4.png)

**Comment by wongsyrone** [comment]
Not a bug, read https://github.com/shadowsocks/shadowsocks-android/blob/master/.github/faq.md#why-does-shadowsocks-consume-so-much-battery-on-android-50
