### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by ucssi-dongxd** [trojan-gfw/igniter#210]
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/61998433/80676524-844eef00-8ae9-11ea-9ff1-d87a2cf31efd.png">
一直提示过时警告。 无法编译

**Comment by ucssi-dongxd** [comment]
<img width="648" alt="image" src="https://user-images.githubusercontent.com/61998433/80676597-b2ccca00-8ae9-11ea-84fd-5a91f3e772de.png">

**Comment by ucssi-dongxd** [comment]
<img width="416" alt="image" src="https://user-images.githubusercontent.com/61998433/80676631-c24c1300-8ae9-11ea-913b-96d06e201357.png">

**Comment by wongsyrone** [comment]
Read CircleCI configuration.
