### ISSUE TITLE
【Suggestion】请支持导出配置文件

### ISSUE THREAD

**Issue by HZGHR** [trojan-gfw/igniter#211]
目前，Igniter只支持从文件导入配置文件（import from file），而不支持导出server list的配置。
建议增加功能：导出Sever list配置到文件

**Comment by HZGHR** [comment]
Currently, Igniter only supports importing configuration from a file, but not exporting server list configuration to a file.
Suggestion: Add the function of exporting Sever list configuration to file.

**Comment by wongsyrone** [comment]
Open PR please.
