### ISSUE TITLE
Does Igniter catch the voice meeting of WeChat?

### ISSUE THREAD

**Issue by dotAge** [trojan-gfw/igniter#219]
In recent days I found that my WeChat got no voice when I join voice meeting. I have to stop the Ignite and rejoin the meeting for the voice working. All other communications working fine, and the voice was fine on a few days ago.
I am not sure this is a matter with Igniter or my Trojan service.

**Comment by oasiscifr** [comment]
Switching on "Exempt Chinese.." or exempting WeChat in App list both do the trick.

**Comment by dotAge** [comment]
The debug apk worked with the Exempt Chinese" enabled! Thanks!
