### ISSUE TITLE
Igniter能否支持这些功能

### ISSUE THREAD

**Issue by okudayukiko** [trojan-gfw/igniter#220]
Android的VpnService并不是直接用iptables或直接读取SOCKS5协议。
1、DNS over TCP。Shadowsocks-Android默认用的是DNS over TCP。有时用DNS over TCP明显加快网速。
2、绕过局域网IP。投影到电视要用到。
3、为服务器命名。有时只填服务器IP无法分辨服务器所在国家。
![Screenshot](https://user-images.githubusercontent.com/17502357/81412050-d9d46d00-9175-11ea-8e98-964239081b43.jpg)

**Comment by oasiscifr** [comment]
@okudayukiko 1,2: already implemented
3: no

**Comment by okudayukiko** [comment]
> @okudayukiko 1,2: already implemented
> 3: no

最新版Igniter（Google Play的版本）没有这些功能。

**Comment by oasiscifr** [comment]
@okudayukiko 
"1" is enabled by default, the remote DNS is your server's DNS server.
"2" is also enable when the "exempt Chinese ..." is switched on.

**Comment by redstoneleo** [comment]
> @okudayukiko
> "1" is enabled by default, the remote DNS is your server's DNS server.
> "2" is enabled when the "exempt Chinese ..." is switched on.

软件上没有明确显示“绕过登陆和局域网地址”的说明，所以即便是有这个功能也还是无法让用户知晓，所以建议把“exempt Chinese ...”改为“绕过登陆和局域网地址”会比较明确

**Comment by redstoneleo** [comment]
@okudayukiko 你是用什么工具投影到电视？
