### ISSUE TITLE
How does "Exempt Chinese Domain" works?

### ISSUE THREAD

**Issue by rfbzs** [trojan-gfw/igniter#226]
Is there a built-in domain list? If so, what about the domains not in the list? Dose igniter resolve those domains to find out their IP addresses just like v2ray?

**Comment by wongsyrone** [comment]
Please check https://github.com/trojan-gfw/igniter/blob/master/app/src/main/res/raw/clash_config.yaml

**Comment by rfbzs** [comment]
Thanks
