### ISSUE TITLE
Doesn't work on Android 10

### ISSUE THREAD

**Issue by chc723** [trojan-gfw/igniter#227]
I just updated from android 9 to 10, and it doesn't work even after I reinstall it.

**Comment by wongsyrone** [comment]
I'm using Samsung S10Plus Android 10 official ROM. I cannot reproduce your issue.

**Comment by TchaikovDriver** [comment]
> I just updated from android 9 to 10, and it doesn't work even after I reinstall it.

Further information about your device is required. BTW, it works well in both of my phones (Android 10). Make sure that battery optimization or any setting that may affect Igniter is disabled.

**Comment by chc723** [comment]
thanks for your reply. I can't find a “log file” or something, so there's little information. My new system is MIUI 11.1.2（based on android 10）, hardware is MI CC9 pro.
Now I try the connection test to google, and it returns “connection closed by peer”.

**Comment by oasiscifr** [comment]
@chc723 Then it is not likely a bug of igniter. Check the pinned issue for further information.

**Comment by fancyChuan** [comment]
> thanks for your reply. I can't find a “log file” or something, so there's little information. My new system is MIUI 11.1.2（based on android 10）, hardware is MI CC9 pro. Now I try the connection test to google, and it returns “connection closed by peer”.

have you resolved it?  I got the same problem
