### ISSUE TITLE
Igniter没有调用ARM AES指令集？

### ISSUE THREAD

**Issue by okudayukiko** [trojan-gfw/igniter#229]
没有调用AES指令集会导致在手机上执行AES加解密速度缓慢和很耗电，以及不稳定。

**Comment by okudayukiko** [comment]
在我的三星手机（Exynos处理器）执行cat /proc/cpuinfo显示
Features: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
没有neon指令集。
执行AES计算很耗电且速度慢。

**Comment by LimiQS** [comment]
AES is not a must-have instruction set on mobile platforms. Enabling AES instrin requires special routine to check support and two versions of code to support either situation. Contribution is welcomed.

**Comment by wongsyrone** [comment]
OpenSSL should already handle it. If you have any questions, please check the OpenSSL source code.

**Comment by okudayukiko** [comment]
> AES is not a must-have instruction set on mobile platforms. Enabling AES instrin requires special routine to check support and two versions of code to support either situation. Contribution is welcomed.

整两份代码其实

**Comment by okudayukiko** [comment]
> AES is not a must-have instruction set on mobile platforms. Enabling AES instrin requires special routine to check support and two versions of code to support either situation. Contribution is welcomed.

通過`cat /proc/cpuinfo`決定CPU是否支援AES指令集，然後執行不同的代碼。或者提供一個開關，優先使用ChaCha20演算法的開關。
