### ISSUE TITLE
android耗电量巨大

### ISSUE THREAD

**Issue by multiplatformsgamer** [trojan-gfw/igniter#232]
最新版android-release包耗电量巨大，掉电速度惊人，跟开了游戏样。如果是因为所有流量都走igniter的话，但我用的ssrr app.从来没有出现过这种情况。
望作者优化

**Comment by cat-walk** [comment]
I encountered the same problem in every android device, hope to be solved in the future version.

**Comment by oasiscifr** [comment]
dup: https://github.com/trojan-gfw/igniter/issues/209

**Comment by okudayukiko** [comment]
Android/iOS 似乎所有VPN都耗电，除了IPsec。因为VPN用了TUN。

**Comment by okudayukiko** [comment]
我的Android 10手機是用半個小時Trojan就耗電10%，還只是瀏覽網頁。

**Comment by okudayukiko** [comment]
Trojan服务端设定：
`vim /etc/trojan/config.json`
`"cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305",`
`"cipher_tls13":  "TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256",`
`#由服务端选择TLS算法`
`"prefer_server_cipher": true,`
`"reuse_session": true,`
`"curves": "X25519:P-256",`

**Comment by okudayukiko** [comment]
Igniter耗电的解决办法有两个：
1、使用ChaCha20算法。
2、可选使用OpenSSL库/SSLEngine库。使用Android OS内置的SSLEngine比OpenSSL快速和省电一些。
