### ISSUE TITLE
I can't build it

### ISSUE THREAD

**Issue by qiutian030618** [trojan-gfw/igniter#237]
I can't Build it beacause I don't clone the cpp libs and trajan's c file
![image](https://user-images.githubusercontent.com/52475894/83972240-948c9200-a911-11ea-8645-c44b8e62b376.png)
![image](https://user-images.githubusercontent.com/52475894/83972253-a1a98100-a911-11ea-8204-e0a97ab2d480.png)
![Uploading image.png…]()

**Comment by wongsyrone** [comment]
Check the CI configuration.
