### ISSUE TITLE
Can't  work  on MIUI12   

### ISSUE THREAD

**Issue by GuoBinV5** [trojan-gfw/igniter#242]
If you update the system version to MIUI12 via MI , Igniter can't connect to trojan server.

**Comment by TchaikovDriver** [comment]
Check app settings and see if there is any restriction on Igniter, such as battery optimization, permission denial or anything else.

**Comment by DenrianWeiss** [comment]
@GuoBinV5 It seems a device-specific issue, since I cannot reproduce on my Mix2s

**Comment by xzchsia** [comment]
It is working well on my Redmi K30 with MIUI12. 
When upgrading to MIUI 12 from MIUI 11, the Google Play always shows error just like "DF-xxx" something like that, then I uninstall the google play and install the latest Google Play, everything will be ok.
