### ISSUE TITLE
ig and whatsapp

### ISSUE THREAD

**Issue by Rspec473** [trojan-gfw/igniter#246]
Instagram not refreshing properly 
whatsapp calls don't connect

**Comment by oasiscifr** [comment]
@Rspec473 App version?

**Comment by Rspec473** [comment]
latest from playstore

humble regards ,
R.Felix

________________________________

**Comment by Rspec473** [comment]
![Screenshot_20200618-203734_Google Play Store](https://user-images.githubusercontent.com/48509709/85020914-9f61e500-b1a3-11ea-9de4-21cee242adff.jpg)

**Comment by wongsyrone** [comment]
Can you uninstall the Google Play variant and install from https://github.com/trojan-gfw/igniter/releases

**Comment by TchaikovDriver** [comment]
> Can you uninstall the Google Play variant and install from https://github.com/trojan-gfw/igniter/releases

There's a bug in v0.9.5 that Igniter would be a global proxy if permission `WRITE_EXTERNAL_STORAGE` is denied.  You'd better release v0.9.6 these days.

**Comment by Rspec473** [comment]
![Uploading Screenshot_20200619-110853_Chrome.jpg…]()

**Comment by Rspec473** [comment]
![Screenshot_20200619-110853_Chrome](https://user-images.githubusercontent.com/48509709/85093407-c5789b00-b21e-11ea-8460-b3ad3c080c6c.jpg)

**Comment by Rspec473** [comment]
no 0.9.6 apk release

**Comment by TchaikovDriver** [comment]
> no 0.9.6 apk release

I was suggesting @wongsyrone release v0.9.6 .

**Comment by wongsyrone** [comment]
Done
