### ISSUE TITLE
使用Google Play Store依舊很慢。

### ISSUE THREAD

**Issue by okudayukiko** [trojan-gfw/igniter#247]
OS：Android 10
下載Android OS更新、下載視頻都速度很快，但下載Google Play Store的App速度很慢。

**Comment by xhrm** [comment]
服务器带宽不够~我这里30mb/ms

**Comment by okudayukiko** [comment]
> 服务器带宽不够~我这里30mb/ms

使用V2Ray又沒這問題

**Comment by okudayukiko** [comment]
> 服务器带宽不够~我这里30mb/ms

用AnyConnect，Google Play Store更新又很快
另外用Trojan看Niconico App經常卡，用AnyConnect無問題。

**Comment by okudayukiko** [comment]
> 服务器带宽不够~我这里30mb/ms

用iOS Shadowrocket的Trojan協議，iOS郵件App的收發郵件也很慢。

**Comment by okudayukiko** [comment]
根據本人測試：
`/etc/trojan/config.json`
`"cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305",`
`"cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256",`
`prefer_server_cipher": false`
若Trojan server有AES-256-GCM算法時，Igniter選擇AES-256-GCM算法；若Trojan server有AES-128-GCM算法時，Igniter選擇AES-128-GCM算法；若Trojan server只有CHACHA20-POLY1305算法，Igniter選擇CHACHA20-POLY1305算法。

**Comment by TchaikovDriver** [comment]
![image](https://user-images.githubusercontent.com/4360392/85221029-19cc7800-b3e3-11ea-8c6f-beefba54eac3.png)
I set `prefer_server_cipher` to `false` and set `cipher` as it is shown above. But I still cannot access Google Play Store. That's weird.

**Comment by okudayukiko** [comment]
> ![image](https://user-images.githubusercontent.com/4360392/85221029-19cc7800-b3e3-11ea-8c6f-beefba54eac3.png)
> I set `prefer_server_cipher` to `false` and set `cipher` as it is shown above. But I still cannot access Google Play Store. That's weird.

我遇到的情況是可以打開Google Play Store，但更新和下載App很慢。Igniter使用CHACHA20-POLY1305加密則問題解決。

**Comment by TchaikovDriver** [comment]
Try the apk [here](https://github.com/TchaikovDriver/igniter/releases/tag/v0.9.6-beta) . Go to exempt app page and select all the packages whose name contains _android_, _google_, _system_. Save the list and see if the issue is solved.

**Comment by okudayukiko** [comment]
另外關於Igniter耗電的問題，我已經將郵件發給oasiscifr，希望開發者查收。

**Comment by oasiscifr** [comment]
@okudayukiko No need to mail me intentionally. We track issues at here.

**Comment by okudayukiko** [comment]
Trojan伺服器僅使用ChaCha20-Poly1305算法：Google Play Store和NicoNico無問題。
Trojan伺服器使用「ChaCha20-Poly1305->AES-GCM, PreferServerCiphers」：問題重現。

**Comment by okudayukiko** [comment]
Trojan/OpenConnect設定TLS ECDHE函數可能會解決看視頻卡必須重連的問題。
`/etc/trojan/config.json`
`"curves": "P-256"`（用`"curves":"X25519:P-256"`或`"curves":""`問題重現）
/`etc/ocserv/ocserv.conf`
tls-priorities = "NONE:+VERS-ALL:+ECDHE-RSA:+ECDHE-ECDSA:+AES-128-GCM:+CHACHA20-POLY1305:+AES-128-CBC:+SHA1:+SHA256:+GROUP-SECP256R1:+CURVE-SECP256R1"（用tls-priorities = "NONE:+VERS-ALL:+ECDHE-RSA:+ECDHE-ECDSA:+AES-128-GCM:+CHACHA20-POLY1305:+AES-128-CBC:+SHA1:+SHA256:+GROUP-X25519:+GROUP-SECP256R1:+CURVE-X25519:+CURVE-SECP256R1"問題重現）

**Comment by okudayukiko** [comment]
選擇Exempt Chinese IPs問題解決。不論Igniter/AnyConnect，解決耗電問題只有跳過中國IP位址，TLS用CHACHA20-POLY1305、AES-CBC-SHA2都沒用。Igniter/AnyConnect用了一個上午後，手機電量從100%變為20%。

**Comment by okudayukiko** [comment]
另外為什麼看TV LIVE（比如NETTV.LIVE）很卡？
