### ISSUE TITLE
加载配置中显示的是服务器地址，建议显示远程服务标识

### ISSUE THREAD

**Issue by lyonghong2020** [trojan-gfw/igniter#252]
加载配置中显示的是服务器地址，这样一来，同一服务器不同端口就只能显示其中一个，建议加载配置中显示的是远程服务标识，谢谢！
![Screenshot_2020-06-24-03-43-31-841_io github trojan_gfw igniter](https://user-images.githubusercontent.com/58104463/85452597-a20e7100-b5cd-11ea-9689-2fb4978a0e5a.jpg)
![Screenshot_2020-06-24-03-43-50-550_io github trojan_gfw igniter](https://user-images.githubusercontent.com/58104463/85452623-ac306f80-b5cd-11ea-8e09-1b4952101b05.jpg)
![Screenshot_2020-06-24-03-43-59-250_io github trojan_gfw igniter](https://user-images.githubusercontent.com/58104463/85452668-b5214100-b5cd-11ea-8e2c-f75b38ff9256.jpg)

**Comment by TchaikovDriver** [comment]
Would be done in the next release.

**Comment by TchaikovDriver** [comment]
#253

**Comment by wongsyrone** [comment]
PR merged into master branch.
