### ISSUE TITLE
请问能增加局域网共享功能吗？

### ISSUE THREAD

**Issue by destiny7** [trojan-gfw/igniter#256]
请问能增加局域网共享功能吗？

**Comment by noobww** [comment]
play上面下一个Proxy Server就是了 https://play.google.com/store/apps/details?id=com.icecoldapps.proxyserver

教程一搜一大把

**Comment by destiny7** [comment]
> play上面下一个Proxy Server就是了 https://play.google.com/store/apps/details?id=com.icecoldapps.proxyserver
> 
> 教程一搜一大把

我试了，但我用switch连不上手机的局域网，我想请问一下，igniter的http端口是58591吗？而且我在trojan win上打开局域网共享也连不上

**Comment by wongsyrone** [comment]
Feature added via https://github.com/trojan-gfw/igniter/releases/tag/v0.10.2-beta
