### ISSUE TITLE
Suggestion建议

### ISSUE THREAD

**Issue by tajackgu** [trojan-gfw/igniter#259]
我用的是华为手机，界面有些不舒服，连接或者断开连接需要翻页，应该是我手机的分辨率不够支持，希望网址密码的间隔距离减小，这样就更加紧凑，连接或者断开连接就在一页里，不用往下滑动了，希望采纳！

**Comment by chen3feng** [comment]
兄弟，保护好自己的域名啊

**Comment by tajackgu** [comment]
> 兄弟，保护好自己的域名啊

谢谢提醒

**Comment by TchaikovDriver** [comment]
#288
