### ISSUE TITLE
配置列表排序问题

### ISSUE THREAD

**Issue by DavidChou92** [trojan-gfw/igniter#262]
v0.9.7-beta
配置列表排序能否优化一下呢？不知道现在是按什么顺序排的，感觉现在的排序有些乱序，希望能按服务器名称或配置名称排序。
![Screenshot_2020-07-14-09-47-00-370_io github trojan_gfw igniter](https://user-images.githubusercontent.com/62595825/87371117-42492b80-c5b7-11ea-93a6-980a580af106.jpg)

**Comment by wongsyrone** [comment]
如果我没记错，按照添加顺序排序

**Comment by TchaikovDriver** [comment]
It depends both the order of servers you add and the order of servers in imported config file. You can rearrange your list in the next release.
See #264 .

**Comment by DavidChou92** [comment]
我使用的订阅模式，可能订阅更新的顺序不对？

**Comment by TchaikovDriver** [comment]
Sorry, as for subscription, the order of profiles is random, because I use a map to ensure remote address uniqueness. 
Would sort them by name in the next release.
