### ISSUE TITLE
请问是否能支持 使用 HAProxy SNI 中转 TLS 节点的功能

### ISSUE THREAD

**Issue by nauya** [trojan-gfw/igniter#268]
使用 HAProxy中转，要求在连接是SNI那添加落地机对应的域名才能使用，单纯的关闭验证证书也没法用，目前trojan Qt5 有这个功能，ios端的小火箭上也有 在peer添加落地机对应的域名。

请问 igniter 是否有支持此功能的计划？

在sspanel上的trojan节点规则示例：中转机域名或IP;port=中转端口|host=落地机对应的域名

**Comment by wongsyrone** [comment]
Remote server SNI configuration is added to 0.9.8-beta, please test if it solves your problem.
