### ISSUE TITLE
Bug報告

### ISSUE THREAD

**Issue by okudayukiko** [trojan-gfw/igniter#275]
版本：Google Play Store最新版。
Bug：
1、若開啟Android的DNS over TLS，則Igniter在斷開VPN連接時就會出現各種Bug。
![20200726_020245](https://user-images.githubusercontent.com/17502357/88463654-d2a43c00-cee6-11ea-90ad-954b562f8e58.jpg)
2、Igniter已保存伺服器列表，長按或往左滑動沒有刪除選項，必須手動點Batch刪除。
![20200726_022747](https://user-images.githubusercontent.com/17502357/88463751-b5bc3880-cee7-11ea-8719-dac5caca295e.jpg)

**Comment by wongsyrone** [comment]
1. https://github.com/shadowsocks/shadowsocks-android/issues/2524
2. Works as expected.
