### ISSUE TITLE
能否不在Task bar顯示「Listening Port」通知？這個Listening Port通知無法左滑清除。無法使用Miracast投影。

### ISSUE THREAD

**Issue by okudayukiko** [trojan-gfw/igniter#277]
Google Play最新版。
對於非root手機而言只能使用VPN模式，現在的Samsung手機難以root。連接後手機左上角的Igniter圖示有些礙眼。雖然可以使用「通知設定」隱藏Igniter圖示。

**Comment by okudayukiko** [comment]
「Exempt Chinese Domain/IPs」勾選了也無法使用Miracast（三星Smart View），無法投影到電視機。

**Comment by TchaikovDriver** [comment]
If you don't want to see the notification, just enter the Igniter's settings and disable the notification.

**Comment by okudayukiko** [comment]
> If you don't want to see the notification, just enter the Igniter's settings and disable the notification.

個人猜測是要排除IPv4、IPv6 LAN IP才能用Miracast。

**Comment by okudayukiko** [comment]
另外有時按START按鈕沒有響應，必須重啟手機。

**Comment by TchaikovDriver** [comment]
@wongsyrone The problem might be caused by [this issue](https://issuetracker.google.com/issues/149636790).

**Comment by HappyMax0** [comment]
最小化通知就行了

**Comment by wongsyrone** [comment]
通知是Android系统要求前台服务的，其实可以关闭通知权限

**Comment by wongsyrone** [comment]
> @wongsyrone The problem might be caused by [this issue](https://issuetracker.google.com/issues/149636790).

这个貌似没有后续了，也不知道是否在修复

**Comment by TchaikovDriver** [comment]
> > @wongsyrone The problem might be caused by [this issue](https://issuetracker.google.com/issues/149636790).
> 
> 这个貌似没有后续了，也不知道是否在修复

shadowsocks-android有给出的[解决方案](https://github.com/shadowsocks/shadowsocks-android/pull/2440/commits/cc840c9fddb3f4f6677005de18f1fcb387b84064)，把原先`VpnService.Buidler.addRoute("::", 0)`替换为`VpnService.Builder.addRoute("2000::", 3);`就行了，但是我没法测试是否可行

**Comment by wongsyrone** [comment]
这个看到过，貌似设置route和它的规则有关，我也没有相应的网络环境。

**Comment by TchaikovDriver** [comment]
[io.github.trojan_gfw.igniter-v0.10.0-beta-SNAPSHOT-230001000-release.zip](https://github.com/trojan-gfw/igniter/files/5148139/io.github.trojan_gfw.igniter-v0.10.0-beta-SNAPSHOT-230001000-release.zip)
@okudayukiko 试一下这个版本，由于安装包的签名不同，需要卸载重装
