### ISSUE TITLE
0.9.8版本设置过滤应用为代理应用模式Google Play无法访问

### ISSUE THREAD

**Issue by SyllableSpec** [trojan-gfw/igniter#279]
0.9.8版本设置过滤应用为代理应用模式Google Play无法访问，选择的其他App没有问题。

**Comment by SyllableSpec** [comment]
Google Play App无法访问，但是其他App可以正常科学上网。

**Comment by TchaikovDriver** [comment]
Check all applications whose names contain _system, android, google_ and try again.

**Comment by wongsyrone** [comment]
`adb logcat Trojan-TUN-lwIP:D TrojanConfig:D Trojan:D trojan:D igniter:D Clash:D ClashConfig:D Go:D GoLog:D VPN:D VpnService:D libc:D DEBUG:D *:S`
