### ISSUE TITLE
0.98版本 启动 过滤大陆域名/IP 之后无法连接

### ISSUE THREAD

**Issue by yangqingmang** [trojan-gfw/igniter#280]
手机：一加7 Pro
Android版本：Android 10
软件版本：0.98 release
现象：点击连接之后，界面变灰，最下方按钮变成正在打开连接，1秒之后界面会闪动一次，再过1秒又闪动一次，然后再等个几秒钟，界面就会变亮，最下方按钮变成 连接
结果：尝试连接google连不上

未打开 过滤大陆域名/IP 则连接正常

**Comment by raymondronaldo** [comment]
It's recommended to clear your app data and reconfigure servers.

**Comment by wongsyrone** [comment]
`adb logcat Trojan-TUN-lwIP:D TrojanConfig:D Trojan:D trojan:D igniter:D Clash:D ClashConfig:D Go:D GoLog:D VPN:D VpnService:D libc:D DEBUG:D *:S`

**Comment by okudayukiko** [comment]
對的，Igniter（Google Play最新版）打開「跳過中國IP/網站」後看YouTube等視頻會變慢（變成馬賽克畫質）
