### ISSUE TITLE
can not work and connect, ask for help

### ISSUE THREAD

**Issue by pda2wham** [trojan-gfw/igniter#282]
igniter can not work and connect like v2rayng in the third OS(such as lineage/aosp...),always shows can 

not connect "www.google.com" SSL handshake time out. I guess probably missing something of GMS, but I don't 

know what it is and don't know how to solve it. so ask for help, thanks

**Comment by pda2wham** [comment]
how to get the logcat? where is the logcat in the phone?

**Comment by TchaikovDriver** [comment]
see #197

**Comment by pda2wham** [comment]
> see #197 

Still don't know how to get, teach me the details please

**Comment by TchaikovDriver** [comment]
You need to install an ADB driver, connect your phone to a computer, then type the following instruction in terminal or command line console:
`adb logcat Trojan-TUN-lwIP:D TrojanConfig:D Trojan:D trojan:D igniter:D Clash:D ClashConfig:D Go:D GoLog:D VPN:D VpnService:D libc:D DEBUG:D *:S > logcat.txt`
Press enter and try to connect Igniter, test connection.
When the test is finished, press `Ctrl + C` to stop collecting log. Upload  `logcat.txt` here.

**Comment by yxp1003** [comment]
did it fixed now？
