### ISSUE TITLE
连接失败，connection closed by peer

### ISSUE THREAD

**Issue by lsh1215225** [trojan-gfw/igniter#286]
今天下午突然就这样了，服务器是正常的，清楚数据再添加配置也没用

**Comment by TchaikovDriver** [comment]
How about reinstalling?

**Comment by lsh1215225** [comment]
> 重新安装怎么样？

之前是0.9.8，已经重新安装了0.9.9，还是这个情况

**Comment by lsh1215225** [comment]
> How about reinstalling?

找到原因了，要关闭验证证书，不过之前都是打开的，不知道为啥现在不能了

**Comment by wongsyrone** [comment]
Please make sure you are using fullchain certification file on the server-side.

**Comment by oasiscifr** [comment]
@lsh1215225 أعتقد أن هذا بسبب انتهاء صلاحية شهادتك اليوم

**Comment by oasiscifr** [comment]
@lsh1215225 I think it’s because your server certificate expired today.
