### ISSUE TITLE
关于中转，有问

### ISSUE THREAD

**Issue by creepppp** [trojan-gfw/igniter#287]
发现一个很尴尬的事：中转的配置只能覆盖不能共存。虽然域名相同，但是端口密码不同啊。。。每次改来改去好麻烦
可以支持共存么？

**Comment by TchaikovDriver** [comment]
下一个版本会支持共存

**Comment by wongsyrone** [comment]
Fixed via https://github.com/trojan-gfw/igniter/commit/49e704c687b4646849af7361252b985abe9dd479
