### ISSUE TITLE
恳请安卓端做几个小改进

### ISSUE THREAD

**Issue by mithew** [trojan-gfw/igniter#289]
1、手机下滑快捷按钮，点按无法触发开和关
2、手机下滑快捷按钮中无法直观看到节点名称

再次感谢！

**Comment by wongsyrone** [comment]
> 手机下滑快捷按钮

这个按钮在哪里

**Comment by mithew** [comment]
> > 手机下滑快捷按钮
> 
> 这个按钮在哪里

快捷开关

**Comment by TchaikovDriver** [comment]
请提供下手机型号和系统版本，另外系统设置中不要限制Igniter的后台活动

**Comment by mithew** [comment]
> 请提供下手机型号和系统版本，另外系统设置中不要限制Igniter的后台活动

小米2s、miui10（安卓9），后台是无限制噢

**Comment by TchaikovDriver** [comment]
> > 请提供下手机型号和系统版本，另外系统设置中不要限制Igniter的后台活动
> 
> 小米2s、miui10（安卓9），后台是无限制噢

进到Igniter app里能正常使用吗

**Comment by wongsyrone** [comment]
Please post logcat: https://github.com/trojan-gfw/igniter/issues/197

**Comment by wongsyrone** [comment]
No response.

**Comment by magic888058** [comment]
下个版本是不是可以考虑支持CDN模式
