### ISSUE TITLE
疑心igniter不允许投屏绕过代理，不知道是不是这样？

### ISSUE THREAD

**Issue by redstoneleo** [trojan-gfw/igniter#290]
我在手机上看YouTube视频，然后投屏到局域网内的电视上，但是投过去之后电视上提示网络差，我疑心igniter不允许投屏绕过代理，不知道是不是这样？

**Comment by TchaikovDriver** [comment]
[io.github.trojan_gfw.igniter-v0.10.0-beta-SNAPSHOT-230001000-release.zip](https://github.com/trojan-gfw/igniter/files/5148488/io.github.trojan_gfw.igniter-v0.10.0-beta-SNAPSHOT-230001000-release.zip)
用这个版本测试一下看看

**Comment by redstoneleo** [comment]
谢谢！问题mei没有改善，我是用UC浏览器投屏（开启了增强模式，如图），
![image](https://user-images.githubusercontent.com/5896180/91734227-3fdd7800-ebdd-11ea-9e53-acf7c999b2b9.png)
测试的是这个视频
https://www.twoeggz.com/movie/15279049.html

开VPN的情况下就会电视上提示网络差，没有开VPN就正常了
