### ISSUE TITLE
Android 11 it could not connect

### ISSUE THREAD

**Issue by Tigerlee100307** [trojan-gfw/igniter#296]
I updated my pixel 2 xl to android 11, it could not connect ,I try to reinstall several times

**Comment by TchaikovDriver** [comment]
Make sure your server works and all the settings are correct. If the problem still occurs, please upload the logcat.

**Comment by Tigerlee100307** [comment]
How to upload the logcat?

**Comment by wongsyrone** [comment]
Please refer to https://github.com/trojan-gfw/igniter/issues/197

**Comment by TchaikovDriver** [comment]
Maybe caused by #310

**Comment by Tigerlee100307** [comment]
The problem is solved, I updated certificate
