### ISSUE TITLE
Play安全信息更新时被识别为使用流量

### ISSUE THREAD

**Issue by noobww** [trojan-gfw/igniter#297]
如题，Clash for Android同样json配置则不会。

igniter 0.9.9 beta ，Android 10

**Comment by wongsyrone** [comment]
I think this method will solve the issue.

ref: https://developer.android.com/reference/android/net/VpnService.Builder#setMetered(boolean)

**Comment by TchaikovDriver** [comment]
> I think this method will solve the issue.
> 
> ref: https://developer.android.com/reference/android/net/VpnService.Builder#setMetered(boolean)

Trying

**Comment by wongsyrone** [comment]
Another ref: https://github.com/shadowsocks/shadowsocks-android/pull/1698

**Comment by zhenchao** [comment]
I see that the code to fix this problem has been merged in the master branch, and I think a new version should be released

**Comment by wongsyrone** [comment]
v0.10.0-beta is released.
