### ISSUE TITLE
Please provide armeabi-only APK

### ISSUE THREAD

**Issue by IzzySoft** [trojan-gfw/igniter#299]
Last release seems to have doubled APK size. Checking the APK I found it holds 4 architectures. Would it be possible to have a separate armeabi-only APK? That would just be a third of the current size then – and thus also help with install issues on devices low on storage. Thanks!

**Comment by wongsyrone** [comment]
Sorry, no plan for this.

**Comment by IzzySoft** [comment]
OK, thanks for checking. Will have to drop it from my repo then, as it exceeds the per-app size limit (30M) by factor 2. Should you reconsider, please let me know and I can reestablish it.

**Comment by wongsyrone** [comment]
The apk size has been reduced via https://github.com/trojan-gfw/igniter/commit/f7e5eb9dfc9061690038325928b5f58f4d029e09

**Comment by IzzySoft** [comment]
Thanks – that's good to hear! Can you give me (raw/approximate) numbers? At the last tagged version it's still 80M, so size rather increased by another 10% since my filing of this issue.

**Comment by wongsyrone** [comment]
The next release apk would be 29.0 MiB (30,455,830 Bytes)

**Comment by IzzySoft** [comment]
Wow, wonderful! That solves the issue for me, thanks!

**Comment by IzzySoft** [comment]
Wow, it's even down to 12M, thanks to your providing the armeabi-only APK! :+1: :star_struck: So I've updated metadata on my end to allow for 2 copies (in case someone needs the previous release for some reason).

But can you tell me why it now needs Android Vision (drawing in dependency on GMS/GooglePlayServices, which are proprietary)? Cannot be the face detection. From the changelog, I guess it's for QR (import/scan). For a FLOSS app (especially one with a "sensitive cause"), maybe it should rather be a FLOSS library? Some examples of possible candidates:

* [ZXing](https://github.com/zxing/zxing/) (Apache-2.0)
* [zxing-android-embedded](https://github.com/journeyapps/zxing-android-embedded) (Apache-2.0)
* [zBarLibary](https://github.com/bertsir/zBarLibary) (MIT)
* [barcodescanner-lib-aar](https://github.com/EddyVerbruggen/barcodescanner-lib-aar) (MIT)
* [barcode-kaiteki](https://github.com/kroegerama/barcode-kaiteki) (Apache-2.0)
* [QRCodeScanner](https://github.com/blikoon/QRCodeScanner) (GPL-3.0)
* [QRCodeScanner](https://github.com/rrifafauzikomara/QRCodeScanner) (AGPL-3.0)
* [easyqrlibrary](https://github.com/mrasif/easyqrlibrary) (GPL-3.0)

I'm no Android developer, so I cannot tell which one would fit your needs (and also not which dependencies those would draw in). But hopefully one of them would match?

**Comment by TchaikovDriver** [comment]
Yes, we migrate from a third party library to ML Kit for QR code scanning. The Vision API you mentioned is a part of ML Kit.
In previous versions, we implemented QR code scanning feature by using a third party library which is based on ZXing.
The major reason that we migrate to ML Kit is that it is an official LTS library from Google. Besides, according to my test result, ML Kit performs better than all the third party libraries I had ever tried.

**Comment by IzzySoft** [comment]
I thought as much. Unfortunately, that Google library is not "libre", and depends on other proprietary Google libraries – which are e.g. not available on Google-free ROMs (custom ROMs like LineageOS, and probably those of Huawei devices as well). Further, there are people who'd consider Google (and other) proprietary dependencies a flaw in an app that should protect their privacy. And that all just for a better performing QR code scanning, I'd consider a high price for a minor win (no offense meant, of course – this is just my personal opinion).

This means that some folks are no longer able to use your app. I guess using two flavors (one with the "better performing" but proprietary-dependant ML Kit, and one with a free/libre solution) would not be feasible? Or "outsourcing" this part to an addon, to keep the main app "untainted"?

**Comment by TchaikovDriver** [comment]
That makes sense. More flavors can do the trick, we will consider your suggestion.

**Comment by IzzySoft** [comment]
Is there any news on this? Or should we rather make a separate issue for it (as this one here is closed, the open point might be forgotten about otherwise :wink:)
