### ISSUE TITLE
Verify certificate: what does it do?

### ISSUE THREAD

**Issue by klzgrad** [trojan-gfw/igniter#3]
I clicked on this button `VERIFY CERTIFICATE` and it didn't seem to do anything.

**Comment by GreaterFire** [comment]
@Atavic This is an old state of code.
@klzgrad The button alters [this](https://github.com/trojan-gfw/igniter/blob/v0.1.0-pre-alpha7/app/src/main/java/io/github/trojan_gfw/igniter/MainActivity.java#L39) option in the config. If it is on, then trojan will verify server certificate based on Mozilla CA extract. If it's off, then server certificate verification is turned off altogether.

**Comment by klzgrad** [comment]
I can see there is a colored bottom border on this button, which is not very obvious. And the border has two colors: red, and black. What do they mean?

Again, I'm not sure why you ever want to not verify certificates in production, which is asking for mitm. Just my 2c.

**Comment by GreaterFire** [comment]
@klzgrad Red means enabled and black means disabled.
For people who generate self-signed certificates, it's a way for them to at least be able to use it. But yeah, it's a huge security issue and we shouldn't recommend that. We could let them specify the certificate they use, but we don't recommend using a self-signed certificate anyways.
