### ISSUE TITLE
旧版本可以用，但是新版本显示  此应用与您的设备不兼容。 直接下载包也无法安装﻿

### ISSUE THREAD

**Issue by ddgjs** [trojan-gfw/igniter#301]
旧版本可以用，但是新版本显示  此应用与您的设备不兼容。 直接下载包也无法安装﻿
[](url)https://www.youtube.com/post/UgycWmBM6W5nU6CsQnN4AaABCQ
[](url)https://www.youtube.com/post/Ugy8L4gPcykSWDf7CnZ4AaABCQ

**Comment by ddgjs** [comment]
[](url)https://www.youtube.com/post/UgycWmBM6W5nU6CsQnN4AaABCQ

**Comment by ddgjs** [comment]
[](url)https://www.youtube.com/post/Ugy8L4gPcykSWDf7CnZ4AaABCQ

**Comment by wongsyrone** [comment]
> Minimum API level bump to Android 6.0
