### ISSUE TITLE
建议增加一键开关小部件

### ISSUE THREAD

**Issue by redstoneleo** [trojan-gfw/igniter#302]
shadowsocks就有这个功能——一键开关小部件，这个小部件未添加到桌面时，在小部件集合里是这样子
![image](https://user-images.githubusercontent.com/5896180/94355818-1586b980-00ba-11eb-8e87-89b4f45ba1d9.png)
添加到桌面上是这样子
![image](https://user-images.githubusercontent.com/5896180/94355824-1fa8b800-00ba-11eb-8785-711af8b8fbcb.png)

具体功能是：点击一下连接VPN，再次点击就断开，太方便了，建议igniter也跟上

**Comment by oasiscifr** [comment]
@redstoneleo We already have a quick avtion tile in the notification bar, which is much easier to use than widgets.

**Comment by redstoneleo** [comment]
how to operate on the avtion tile？

**Comment by TchaikovDriver** [comment]
![mmexport1601213750503.jpg](https://user-images.githubusercontent.com/4360392/94366254-8acdab00-0109-11eb-956d-b28a6deef2dc.jpg)
Slide down the menu and edit your tiles, find and drag Igniter tile to anywhere you like.

**Comment by redstoneleo** [comment]
There is no Igniter tile on my Android phone,  which Android version are you using ?
BTW, I still think the toggle switch on home screen is much convenient , please give further consideration on implementing this feature

**Comment by TchaikovDriver** [comment]
> There is no Igniter tile on my Android phone, which Android version are you using ?
> BTW, I still think the toggle switch on home screen is much convenient , please give further consideration on implementing this feature
> 
> @TchaikovDriver I think you should remove your QQMail and donation QR code on [your blog](https://tchaikovdriver.github.io/) for your personal safety and privacy

Igniter's quick setting tile feature is available since `Android 7.1.1`.  No worry about the personal information in my blog, merely nobody visit my blog since it was born, and so did I. All pictures are not available anymore, so sad.

**Comment by redstoneleo** [comment]
Some customized Android OS dose not keep the tile feature, so is the one owned by me. Besides, adding the toggle shortcut on screen doesn't increase the  complexity to igniter users , but rather introduce convenience , so please give another consideration on implementing this feature

**Comment by redstoneleo** [comment]
@TchaikovDriver Since you are one of the active developers of this project , you'd better hide yourself in risk of being found by the Big Brother of PRC.

**Comment by TchaikovDriver** [comment]
Thanks for your advice, already closed my poor blog. I will develop the
shortcut feature when I am spare.

redstoneleo <notifications@github.com> 于 2020年9月30日周三 下午9:18写道：
