### ISSUE TITLE
0.99版本bypass China domain有缺陷

### ISSUE THREAD

**Issue by xbh** [trojan-gfw/igniter#304]
最新版本的bypass China domain/ IP 并不能准确分流。百度，微信，哔哩哔哩，ip.cn等网站流量依旧被代理。但部分网站如站长之家可以被正常识别并且bypass。查看log，有正确DIRECT（GEOIP CN）的流量产生。我猜测可能是geoip数据库过时了

**Comment by oasiscifr** [comment]
@xbh Can you test it again in an ipv4-only network environment?

**Comment by wongsyrone** [comment]
@xbh Please clear your app data and cache and try again.

**Comment by xbh** [comment]
> @xbh Can you test it again in an ipv4-only network environment?

I tested, still the same.

**Comment by xbh** [comment]
> @xbh Please clear your app data and cache and try again.

I tried to clear data when I found problem, I also tried to reinstall the both 0.9.9 and 0.9.8 apk. Still jave the same issue.

**Comment by wongsyrone** [comment]
Please disable Private DNS on Android, it uses DoT or DoH, Clash (the internal traffic classifier) cannot handle the connection based on the domain name, it got resolved IP address. To turn off the feature, go to Settings->Network & Internet->Advanced. In there, you will see an option for Private DNS, which should be Off.

**Comment by oasiscifr** [comment]
@wongsyrone 👍
