### ISSUE TITLE
Android 11 - 'Exempt Apps' Functions, can not load all apps

### ISSUE THREAD

**Issue by regusername** [trojan-gfw/igniter#310]
When my Pixel 3XL running Android 10, it works very well.
But after I upgrade to Android 11, the 'Exempt Apps' Functions, can not load all apps that I installed, only parts of the apps can be seen. whatever 'Block Mode' or 'Allow Mode'.
Ver 0.9.9 could not load all apps.
Upgrade to Ver 0.10.0 also the same.

**Comment by doegeenon** [comment]
Same issue on my Pixel 2 XL with Android 11, while is all good on my Pixel 2016 running Android 10

**Comment by TchaikovDriver** [comment]
Will be fixed in the next release.

**Comment by TchaikovDriver** [comment]
#311

**Comment by rurirei** [comment]
see this https://github.com/2dust/v2rayNG/pull/691

**Comment by wongsyrone** [comment]
> see this [2dust/v2rayNG#691](https://github.com/2dust/v2rayNG/pull/691)

@TchaikovDriver any thought?

**Comment by rurirei** [comment]
> > see this [2dust/v2rayNG#691](https://github.com/2dust/v2rayNG/pull/691)
> 
> @TchaikovDriver any thought?

requires review by Google recommended, or create a list like ApplicationList to query those.

**Comment by wongsyrone** [comment]
> requires review by Google recommended, or create a list like ApplicationList to query those.

I don't understand. The app is reviewed by Google and distributed on Google Play Store.

**Comment by TchaikovDriver** [comment]
> > see this [2dust/v2rayNG#691](https://github.com/2dust/v2rayNG/pull/691)
> 
> @TchaikovDriver any thought?
> 

The permission is already declared in AndroidManifest. It is not a "dangerous" permission but when Igniter is distributed on Google Play, it may need to request a review by Google. I don't know how to request though.

**Comment by wongsyrone** [comment]
> The permission is already declared in AndroidManifest. It is not a "dangerous" permission but when Igniter is distributed on Google Play, it may need to request a review by Google. I don't know how to request though.

When I upload new releases, it shows "Under Review" each time and we passed the stage, can I assume the new permission is already granted by Google and we don't have to request it? I cannot find any guide on doing so.

**Comment by TchaikovDriver** [comment]
> When I upload new releases, it shows "Under Review" each time and we passed the stage, can I assume the new permission is already granted by Google and we don't have to request it? I cannot find any guide on doing so.

Well, since we passed the review, Igniter downloaded from Google Play is able to read all the installed applications.
