### ISSUE TITLE
Use ML kit for qrcode scanning

### ISSUE THREAD

**Issue by wongsyrone** [trojan-gfw/igniter#312]
Pros:
- Google official support library

Cons:
- Increase APK size
- This is a beta release of ML Kit. This API might be changed in backward-incompatible ways and is not subject to any SLA or deprecation policy.

ref: https://developers.google.com/ml-kit/vision/barcode-scanning
ref impl: https://github.com/shadowsocks/shadowsocks-android/pull/2551

**Comment by TchaikovDriver** [comment]
Interesting, I would have a try.

**Comment by TchaikovDriver** [comment]
#313
