### ISSUE TITLE
Issue with Google Translate and Ignitor

### ISSUE THREAD

**Issue by xenstar** [trojan-gfw/igniter#316]
Hello, when I am using ignitor, the image import in Google translate (Android) function doesn't work, but with v2rayng it works. 

This is a very important function for foreigners. I am not sure what is the issue exactly. I give the screenshot, below. 

![Screenshot_2020-10-21-11-05-44-008_com.google.android.apps.translate.jpg](https://user-images.githubusercontent.com/55502651/96668489-db919600-138d-11eb-9dbb-862d4513a507.jpg)

![Screenshot_2020-10-21-11-06-07-829_com.google.android.apps.translate.jpg](https://user-images.githubusercontent.com/55502651/96668523-e9dfb200-138d-11eb-8333-b39aea302bb1.jpg)

**Comment by wongsyrone** [comment]
I tried Google Translate and cannot reproduce your issue. Please clear your app data and cache and try again.

**Comment by xenstar** [comment]
Sorry because I post it from my phone last time, so I couldn't maybe explain.

You see I have posted two pictures.

The first picture is, when I use Igniter and HK Tencent Server, you can see on the bottom there is no "Instant Scan Import" Icon. Once I open the app, I have cleared cache, uninstall and install it again, same issue, this option doesn't show.

In the 2nd picture, when I am using v2rayNG HGC HK Server, you can see the "Instant Scan Import" icon is showing, and I can use the image search function.

For you to check it, you need to download google translate, select Chinese to English, and see if you can see this 3 icon or not. 

I am assuming while using Igniter "It's using China Server for translate, so that's why maybe the Icons are not showing, because maybe while accessing google translate through China IP, they restrict image upload function".

**Comment by wongsyrone** [comment]
> For you to check it, you need to download google translate, select Chinese to English, and see if you can see this 3 icon or not.

Yes, I can. I mean clear your Igniter data and cache and retry.

**Comment by xenstar** [comment]
Tried with igniter cache and cleared, all data cleared, and fresh install. Didnt work. Some weird.

**Comment by oasiscifr** [comment]
@xenstar Maybe we need a Xen Grenade. 😉 Can you access google translate directly from your trojan server?

**Comment by xenstar** [comment]
@oasiscifr From the URL, like in desktop, global mode, I can access.

**Comment by TchaikovDriver** [comment]
Did you try **2.3** in #197 ?

**Comment by wongsyrone** [comment]
Close due to no response
