### ISSUE TITLE
最新版会导致无法连接谷歌服务

### ISSUE THREAD

**Issue by HappyMax0** [trojan-gfw/igniter#317]
国行三星手机（刻意屏蔽FCM推送，只有挂梯后才能接收FCM推送），用了最新版igniter一段时间后，会出现无法连接所有Google应用、收不到FCM推送的问题，而网页版Google和其它应用都能连接上。

**Comment by wongsyrone** [comment]
I'm using a Samsung phone and cannot reproduce your issue.

**Comment by wongsyrone** [comment]
Close due to no response

**Comment by HappyMax0** [comment]
打开下载管理器的允许在后台随意使用流量，允许在后台运行就好了。
