### ISSUE TITLE
The password in the share url is not encoded in url-encode

### ISSUE THREAD

**Issue by nekohasekai** [trojan-gfw/igniter#318]
```
The trojan URL scheme is defined (not finalized) as such:

trojan://password@remote_host:remote_port

in which the password is url-encoded in case it contains illegal characters.
```

![IMG_20201022_103122](https://user-images.githubusercontent.com/56506714/96817367-c120f080-1451-11eb-9b99-0a533ccb117d.jpg)

**Comment by wongsyrone** [comment]
Should be fixed via https://github.com/trojan-gfw/igniter/commit/f1faa250b019224e0afdd5cb959c9d2dde4f6a3d
