### ISSUE TITLE
igniter自0.10以后的版本的BUG

### ISSUE THREAD

**Issue by amie1972** [trojan-gfw/igniter#321]
自从升级到0.10以后的版本后，该程序已经不能正确解析订阅链接了。就是说，输入正确的订阅链接后，不能正确更新订阅。

**Comment by wongsyrone** [comment]
> 正确的订阅链接

Igniter 是 trojan-gfw 官方客户端，只支持官方特性，对于订阅链接，无相关官方规范存在，目前使用的为贡献者无偿提供的，若与服务商使用的规范不同则不算客户端本身bug。

根据代码说明，只支持如下格式订阅：

> Only supports data in format 'TrojanUrl1#remark\nTrojanUrl2#remark\n...' (decoded in BASE64)

ref: https://github.com/trojan-gfw/igniter/commit/b5e5aa42ea1febbe3d6562a14e96055cbd8e987c

**Comment by amie1972** [comment]
但是这个问题只是从0.10版本开始才出现，之前的版本则能够正常解析。

**Comment by amie1972** [comment]
我如果删除掉新版本的该程序而安装旧版本的程序则能够正确解析同样的订阅链接。

**Comment by wongsyrone** [comment]
可以将订阅链接访问结果base64解码后，去除敏感信息发到这里，也可以将订阅链接私发至我的邮箱 wong.syrone@gmail.com

**Comment by amie1972** [comment]
邮件已发。

**Comment by wongsyrone** [comment]
好的，回家我在测试

**Comment by wongsyrone** [comment]
请测试该版本，如无问题会成为下个发布版本

https://github.com/trojan-gfw/igniter/issues/315#issuecomment-723548704

**Comment by amie1972** [comment]
谢谢，这个版本没有问题了。



在 2020-11-09 18:29:55，"Syrone Wong" <notifications@github.com> 写道：

请测试该版本，如无问题会成为下个发布版本

#315 (comment)
