### ISSUE TITLE
0.10.2加载西部世界的trojan订阅后，节点中文名称全部乱码展示  

### ISSUE THREAD

**Issue by ShadowWalker627** [trojan-gfw/igniter#323]
%E5%95%86%E5%8A%A1%C2%B7%E6%96%B0%E5%8A%A0%E5%9D%A1SP%C2%B7IPLC%E4%B8%93%E7%BA%BF%C2%B7%E7%A6%81%E8%A7%86%E9%A2%91%C2%B7%E7%A9%BA%E9%97%B2%C2%B710%E5%80%8D%C2%B71000M

以上为乱码

**Comment by wongsyrone** [comment]
此处节点备注使用了URL百分号编码，但Trojan官方URL规范中并无相关说明，故而不算bug

**Comment by suemyass** [comment]
这个要如何解决

**Comment by suemyass** [comment]
> %E5%95%86%E5%8A%A1%C2%B7%E6%96%B0%E5%8A%A0%E5%9D%A1SP%C2%B7IPLC%E4%B8%93%E7%BA%BF%C2%B7%E7%A6%81%E8%A7%86%E9%A2%91%C2%B7%E7%A9%BA%E9%97%B2%C2%B710%E5%80%8D%C2%B71000M
> 
> 以上为乱码

我的也是西部世界 不知如何处理

**Comment by wongsyrone** [comment]
Should be fixed via https://github.com/trojan-gfw/igniter/commit/cb884ea0b362b115db26abb0136bb4cee22a459f and https://github.com/trojan-gfw/igniter/commit/b822effaeb6c78d846730e3d856c65b1dc670a04.

We don't have such spec on the server remark, no guarantee on the feature.
