### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by BoyceLig** [trojan-gfw/igniter#324]
1. 带备注的链接不能被导入备注
2. 多个链接同时复制不能同时导入配置，需要用摄像机一个一个去扫码添加配置
3. 希望一进去是配置界面，而不是节点编辑界面，方便换节点，连接也移动到配置界面。因为感觉编辑节点的界面实在少用。（建议）
4. 点击连接后再点断开连接，再次点击连接就无反应了
5. 当配置界面里有多个节点，再想手动添加节点就只能导入或者扫码了，不能手动输入创建
6. 在logcat中显示开发信息点击无效
7. 关于界面的所有地址没有超链接跳转到网页，也不能进行复制

**Comment by TchaikovDriver** [comment]
- 导入链接本身没有规范，如果需要支持带备注至少要给出链接格式。
- 要导入多个服务器的话建议直接导入配置文件。
- 点击连接没反应的问题麻烦提供一下logcat

**Comment by BoyceLig** [comment]
> * 导入链接本身没有规范，如果需要支持带备注至少要给出链接格式。
> * 要导入多个服务器的话建议直接导入配置文件。
> * 点击连接没反应的问题麻烦提供一下logcat

是按照v2ray的导出格式导出的
例如：trojan://Trojan-MoonVM@trojan.com:443#%E5%8F%B0%E6%B9%BE-%E5%8A%A8%E6%80%81IP%E6%9C%8D%E5%8A%A1%E5%99%A8-100Mbps
#后面是备注，前面是节点信息，是通用的（节点已做处理，不能连接）

应该是可以复现吧 只有我自己有这个问题么
logcat怎么导出

**Comment by TchaikovDriver** [comment]
我用手头上的Igniter测试是可以导入的
