### ISSUE TITLE
[Feature Request]希望增加替换geoip文件功能与自定义规则编辑功能

### ISSUE THREAD

**Issue by SekiBetu** [trojan-gfw/igniter#326]
如题，在目前的使用中我发现有部分网站分流不精准，不该代理的国内网站被代理了，

而如果去使用分应用的代理方式，则因其一刀切的特点，十分不方便，
例如使用telegram时打开内置浏览器浏览国内网站会被代理导致访问速度变慢，访问IP也是代理IP

因此，希望用户能够使用自定义的geoip文件，例如以下项目：
https://github.com/Loyalsoldier/v2ray-rules-dat

并且能够自定义编辑geoip的规则，这样能够更加精准地分流

其他项目也有过类似的提案并且已经被实现，可作为参考：
https://github.com/2dust/v2rayNG/pull/662
注：安卓11可能有点问题，附加以下资料以供参考
https://source.android.com/devices/storage/scoped
https://developer.android.com/about/versions/11/privacy/storage

分流代理是本时代代理软件的重要特性，我认为设计客户端时应当是要优先考虑的

**Comment by wongsyrone** [comment]
Duplicate https://github.com/trojan-gfw/igniter/issues/114

**Comment by lixian13149999** [comment]
看到类似的功能有过滤应用，但是设置起来太麻烦了
