### ISSUE TITLE
【过滤大陆域名/IP】不起作用，勾选和不勾选流量全部都是走代理？

### ISSUE THREAD

**Issue by dustreading** [trojan-gfw/igniter#329]
【过滤大陆域名/IP】并没有起到作用，我经过测试，发现这个选项勾选和不勾选都一样，流量都是走代理，根本不会过滤大陆域名/IP，大家有和我一样的情况吗？

**Comment by wongsyrone** [comment]
个人建议 #329 和 #330 的同学互相交流一下

**Comment by poooower** [comment]
> 个人建议 #329 和 #330 的同学互相交流一下

确实有问题,过滤app是好的,过滤ip不行

**Comment by wongsyrone** [comment]
Close due to no log attached.
