### ISSUE TITLE
网上有支持TROJAN的V2rayN 是什么回事？

### ISSUE THREAD

**Issue by gbmeco** [trojan-gfw/igniter#33]
网上看到有介绍Trojan 的客户端，但应该是V2rayN修改的。没敢下，有人知道是怎么回事吗？

介绍页面
https://westworldss.com/portal/page/trojan

下载链接。
https://westworldss.com/download/v2rayN-win-with-trojan-v2.zip

**Comment by oasiscifr** [comment]
@gbmeco read the docs carefully
