### ISSUE TITLE
有dns泄露的问题

### ISSUE THREAD

**Issue by jj-a-li** [trojan-gfw/igniter#331]
连接后，本机dns和服务器dns同时可查询

**Comment by jj-a-li** [comment]
![IMG_20201127_071409](https://user-images.githubusercontent.com/72844255/100396486-2d5dc800-3080-11eb-8400-b26751dadc68.jpg)

**Comment by jj-a-li** [comment]
![Uploading IMG_20201127_071409.jpg…]()

**Comment by oasiscifr** [comment]
Interesting issue, but more information is needed. What software is this? What specific problems does the result indicate?
