### ISSUE TITLE
大前天开始无法使用

### ISSUE THREAD

**Issue by coldshineb** [trojan-gfw/igniter#332]
电脑连接正常，手机上无法使用，已测试三台手机，华为荣耀4X EMUI安卓6、华为荣耀6X 原生安卓9和另外一台安卓10手机，三台手机分别在校园网、移动宽带、移动4G、电信宽带下测试，清除软件数据无效果。

**Comment by kowenzhang** [comment]
Mate20， 2个月没法用了，测试了v0.9.1和v0.10.2都不行，是不是被华为“优化”了。

**Comment by wongsyrone** [comment]
Close due to no detailed log.
