### ISSUE TITLE
编译报错，是什么东西没配置好吗

### ISSUE THREAD

**Issue by yujian016** [trojan-gfw/igniter#334]
Build command failed.
Error while executing process D:\sdk\cmake\3.10.2.4988404\bin\ninja.exe with arguments {-C E:\trojan\igniter\app\.cxx\cmake\debug\armeabi-v7a jni-helper}
ninja: Entering directory `E:\trojan\igniter\app\.cxx\cmake\debug\armeabi-v7a'

ninja: error: 'E:/trojan/igniter/app/src/main/cpp/libs/lib/armeabi-v7a/libboost_program_options.a', needed by 'libjni-helper.so', missing and no known rule to make it

**Comment by wongsyrone** [comment]
https://github.com/trojan-gfw/igniter/blob/master/.circleci/config.yml
