### ISSUE TITLE
Build command failed

### ISSUE THREAD

**Issue by yujian016** [trojan-gfw/igniter#335]
Build command failed.
Error while executing process D:\sdk\cmake\3.10.2.4988404\bin\ninja.exe with arguments {-C E:\trojan\igniter\app\.cxx\cmake\debug\arm64-v8a jni-helper}
ninja: Entering directory `E:\trojan\igniter\app\.cxx\cmake\debug\arm64-v8a'
[1/1] Linking CXX shared library libjni-helper.so
FAILED: libjni-helper.so 
cmd.exe /C "cd . && D:\sdk\ndk\22.0.6917172\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android23 --gcc-toolchain=D:/sdk/ndk/22.0.6917172/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=D:/sdk/ndk/22.0.6917172/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -frtti -fexceptions  -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libjni-helper.so -o libjni-helper.so CMakeFiles/jni-helper.dir/jni-helper.cpp.o  libtrojan.a E:/trojan/igniter/app/src/main/cpp/libs/lib/arm64-v8a/libboost_program_options.a E:/trojan/igniter/app/src/main/cpp/libs/lib/arm64-v8a/libboost_system.a E:/trojan/igniter/app/src/main/cpp/libs/lib/arm64-v8a/libssl.a E:/trojan/igniter/app/src/main/cpp/libs/lib/arm64-v8a/libcrypto.a -llog -latomic -lm && cd ."
ld: error: relocation R_AARCH64_PREL64 cannot be used against symbol OPENSSL_armcap_P; recompile with -fPIC
>>> defined in E:/trojan/igniter/app/src/main/cpp/libs/lib/arm64-v8a/libcrypto.a(armcap.o)
>>> referenced by chacha-armv8.o:(.text+0x20) in archive E:/trojan/igniter/app/src/main/cpp/libs/lib/arm64-v8a/libcrypto.a

ld: error: relocation R_AARCH64_PREL64 cannot be used against symbol OPENSSL_armcap_P; recompile with -fPIC
>>> defined in E:/trojan/igniter/app/src/main/cpp/libs/lib/arm64-v8a/libcrypto.a(armcap.o)
>>> referenced by poly1305-armv8.o:(.text+0x9A0) in archive E:/trojan/igniter/app/src/main/cpp/libs/lib/arm64-v8a/libcrypto.a

ld: error: relocation R_AARCH64_PREL64 cannot be used against symbol OPENSSL_armcap_P; recompile with -fPIC
>>> defined in E:/trojan/igniter/app/src/main/cpp/libs/lib/arm64-v8a/libcrypto.a(armcap.o)
>>> referenced by sha1-armv8.o:(.text+0x1240) in archive E:/trojan/igniter/app/src/main/cpp/libs/lib/arm64-v8a/libcrypto.a

ld: error: relocation R_AARCH64_PREL64 cannot be used against symbol OPENSSL_armcap_P; recompile with -fPIC
>>> defined in E:/trojan/igniter/app/src/main/cpp/libs/lib/arm64-v8a/libcrypto.a(armcap.o)
>>> referenced by sha256-armv8.o:(.text+0xF88) in archive E:/trojan/igniter/app/src/main/cpp/libs/lib/arm64-v8a/libcrypto.a

ld: error: relocation R_AARCH64_PREL64 cannot be used against symbol OPENSSL_armcap_P; recompile with -fPIC
>>> defined in E:/trojan/igniter/app/src/main/cpp/libs/lib/arm64-v8a/libcrypto.a(armcap.o)
>>> referenced by sha512-armv8.o:(.text+0x1108) in archive E:/trojan/igniter/app/src/main/cpp/libs/lib/arm64-v8a/libcrypto.a
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by wongsyrone** [comment]
Sorry, Windows is not supported.
