### ISSUE TITLE
igniter允许局域网访问

### ISSUE THREAD

**Issue by pengajiang** [trojan-gfw/igniter#344]
开启局域网访问后，其他开启个人热点就行了吗？状态栏也没用显示目前监听端口，其他设备上应如何配置呢？

**Comment by TchaikovDriver** [comment]
Igniter的通知上不是有显示端口吗？

**Comment by storytellerF** [comment]
安装igniter的设备开启热点，其他设备连接
其他设备需要安装能够添加socks连接的应用（如v2ray），端口在会在igniter的通知中告知

**Comment by liuge067** [comment]
我的手机是安卓7开启了局域网访问之后通知里也没显示本地端口啊，请问一下igniter的本地端口是多少？
