### ISSUE TITLE
VPN sharing via cellphone hotapot

### ISSUE THREAD

**Issue by RoyHANABI** [trojan-gfw/igniter#348]
First of all I wanna say thanks for creating this useful tool. Sometimes I need to use laptop to connect internet via a VPN which is running in mobile device, but when I launch the hotspot and connect to the cellphone, it's not working as I imagined.  I found some app called VPN hotspot but sadly it's root required...I wish you would consider solving this issue ;)

**Comment by oasiscifr** [comment]
@RoyHANABI ASAIK it's impossible without root.

**Comment by RoyHANABI** [comment]
Thanks @oasiscifr I'll try that but it's grateful to hear that if Igniter can do the same.

**Comment by RoyHANABI** [comment]
hmm...it's sad...ಥ_ಥ
