### ISSUE TITLE
给个关于局域网连接端口的建议

### ISSUE THREAD

**Issue by liuge067** [trojan-gfw/igniter#349]
我发现一些手机通知里不能显示igniter的本地连接端口，就算能显示的每次断开之后再连接端口都是随机的。如果可以的话希望作者大人可以固定一个端口或者给一个随意让我们改动本地端口数字的功能就太好了。

**Comment by TchaikovDriver** [comment]
目前每次建立连接的端口都是随机的，我可以做一个设置页面让用户选择随机端口还是固定端口

**Comment by wongsyrone** [comment]
随机端口的初衷是避免端口占用导致的各种奇葩问题，用户自己指定需要确保无占用

**Comment by wongsyrone** [comment]
> 随意让我们改动本地端口数字

这个功能不考虑实现

**Comment by zoozooll** [comment]
那么是否可以考虑，在本应用内可以看到这次启动时候的端口，而不仅仅在通知栏

**Comment by TchaikovDriver** [comment]
> 那么是否可以考虑，在本应用内可以看到这次启动时候的端口，而不仅仅在通知栏

这个可以，我放到主界面里，提供个一键复制按钮

**Comment by liutf** [comment]
> 目前每次建立连接的端口都是随机的，我可以做一个设置页面让用户选择随机端口还是固定端口

我现在每天都需要使用Chrome SwitchyOmega 打开igniter，但是igniter的端口每次都是随机的，我都要手动去填写一次端口号，很麻烦。请问现在可以固定个端口号吗？

![image](https://user-images.githubusercontent.com/14069370/155863735-df0a7900-5e86-4f93-b1df-88a94fc075b0.png)
