### ISSUE TITLE
 Cause: executing external native build for cmake /igniter/app/src/main/cpp/CMakeLists.txt

### ISSUE THREAD

**Issue by qqhaodong** [trojan-gfw/igniter#35]
Android Studio run build the project with sync have a problem 
ERROR: Cause: executing external native build for cmake /igniter/app/src/main/cpp/CMakeLists.txt
what's wrong?how can i run build it?

**Comment by wsad137** [comment]
I also met，use tag v0.1.0-pre-alpha10 is ok.

**Comment by qqhaodong** [comment]
thanks，i will try it...
