### ISSUE TITLE
Where to input username

### ISSUE THREAD

**Issue by AlbertSnow** [trojan-gfw/igniter#351]
Hello developer:
   Where I can input my torjan account  user name. I can see the main page of app just have 5 row:  1. 远程服务备注 2.远程地址 3.远程服务SNI 4.端口号 6.密码。
   So where I can input me trojan account user name.

**Comment by wongsyrone** [comment]
This is no such thing as trojan accounts neither user name.

**Comment by AlbertSnow** [comment]
... But I already solve the problem. The first row is the View that input user name.  
Maybe the view can input any word, but at least input user name is valid.
