### ISSUE TITLE
虽然最后生成了apk，但是有java报错

### ISSUE THREAD

**Issue by JoneJay** [trojan-gfw/igniter#354]
igniter\exempt\data\ExemptAppDataManager.java:138: ����: [deprecation] PackageManager�е�GET_DISABLED_COMPONENTS�ѹ�ʱ
            flags |= PackageManager.GET_UNINSTALLED_PACKAGES | PackageManager.GET_DISABLED_COMPONENTS;

java1.8 
androidstudio4.2
gradle 6.6 plugin 4.1.2

**Comment by TchaikovDriver** [comment]
这仅仅是个deprecation的warning，如果你去看这部分源码，能看到注释里解释了为什么要引用这两个常量。
