### ISSUE TITLE
0.10.2-beta  works unstablely on XioaMi cc9pro , and 0.10.1-beta works ok.

### ISSUE THREAD

**Issue by silenwoods** [trojan-gfw/igniter#356]
0.10.2-beta  works unstablely on XioaMi cc9pro , and 0.10.1-beta works ok.
MIUI version: 12.1.5

0.10.0 also works ok, but cannot get full app list.

**Comment by TchaikovDriver** [comment]
What do you mean by _unstable_ ?

**Comment by wongsyrone** [comment]
Post the log, please.

**Comment by wongsyrone** [comment]
Reopen when you can provide detailed information.
