### ISSUE TITLE
0.10.3-beta版本，打开或者关闭 过滤大陆域名/ip 的开关，没有任何作用，还是通过远程服务器连的国内网。

### ISSUE THREAD

**Issue by JoneJay** [trojan-gfw/igniter#357]

**Comment by JoneJay** [comment]
搞错了，浏览器问题

**Comment by JoneJay** [comment]
又试了下还是有问题，问题在于浏览器，用手机自带的浏览器没问题，但是chrome就是不行，配置为 打开过滤大陆域名/IP , 第一次打开浏览器的时候在ip138显示正常国内ip，但是打开个国内网址的视频（在浏览器）看一会后，服务端就收到包了，再去138看ip地址竟然变成了国外的了，但是却能访问局域网的地址，不知道chrome做了什么。

**Comment by wongsyrone** [comment]
Chrome关闭省流量

**Comment by wongsyrone** [comment]
使用安全DNS（Use secure DNS）也关掉
