### ISSUE TITLE
when is the next release coming?

### ISSUE THREAD

**Issue by raydio991** [trojan-gfw/igniter#359]
如题，下个发行版啥时候出

**Comment by wongsyrone** [comment]
issue区有太多的未解之谜，未发布的版本和发布的没有明显提升，暂时还没有发布计划

**Comment by TchaikovDriver** [comment]
> issue区有太多的未解之谜，未发布的版本和发布的没有明显提升，暂时还没有发布计划

话说我那个PR还合并不，不合的话我关掉吧

**Comment by wongsyrone** [comment]
@TchaikovDriver 还没仔细看，这周末弄
