### ISSUE TITLE
0.10.2-beta，手机浏览器都可以用，但是app无法用

### ISSUE THREAD

**Issue by xiaozijun** [trojan-gfw/igniter#360]
比较奇怪，第一次安装的时候，app是可以用的，youtube，play商店都可以，然后也没过多久就只能用浏览器了，app好像都失效了，请问这个是属于我没配置好吗？

**Comment by TchaikovDriver** [comment]
看 #197

**Comment by wongsyrone** [comment]
Reopen when you can provide detailed information.
