### ISSUE TITLE
[BUG]在夜间模式下，DNS设置页面显示异常

### ISSUE THREAD

**Issue by XfZGGG** [trojan-gfw/igniter#367]
Android 10
igniter 0.10.3-beta
系统开启全局夜间(暗黑模式)时，DNS设置页面显示异常。
![photo_2021-05-04_21-40-58](https://user-images.githubusercontent.com/81817524/117012986-0b006280-ad22-11eb-9f21-659dd7080ca4.jpg)
![photo_2021-05-04_21-40-54](https://user-images.githubusercontent.com/81817524/117013022-12277080-ad22-11eb-8fa8-5e9bf4f4e913.jpg)

**Comment by TchaikovDriver** [comment]
Already fixed in the next release.
