### ISSUE TITLE
在鸿蒙OS2上不工作 兼容问题

### ISSUE THREAD

**Issue by HaliComing** [trojan-gfw/igniter#386]
version 0.10.3
希望修复兼容问题，在鸿蒙OS2上点击连接后，当打开Google后，它将正常工作一次，我顺利的看到了Google页面，之后就不正常工作了。无法加载页面，然后退出Igniter，重新打开，再重新连接后，又可以正常工作一次。
手机 HUAWEI Mate 30 5G. 升级鸿蒙OS2前，一切正常。升级后出现问题。Igniter重新安装仍然存在此问题。

**Comment by wongsyrone** [comment]
本人不使用华为设备，无鸿蒙系统，希望有设备的人员帮助获取log等调试或错误信息。

**Comment by HaliComing** [comment]
错误信息我应如何提供获取？我认为我可以帮助你。

**Comment by wongsyrone** [comment]
https://github.com/trojan-gfw/igniter/discussions/373 从这里看adb logcat，或者连接手机开发者模式，使用Android Studio调试

**Comment by HaliComing** [comment]
我使用了#373 我发现当我使用ADB logcat后，我进行测试访问，google和github等页面连接状态良好，速度很快。当我断开adb logcat后，重新尝试，发现连接稳定性又下降了。对了，我能上传我的日志吗，因为里面好像保存的有连接信息

**Comment by wongsyrone** [comment]
> 我能上传我的日志吗，因为里面好像保存的有连接信息

可以上传，只去掉自己服务器的IP，密码等敏感信息即可

**Comment by HaliComing** [comment]
以下是日志，我经过多次测试，发现adb期间可以很好的代理，但是断开调试后连接，代理就不稳定了。而且有一个奇怪的现象，就是，我打开igniter工具点击连接后，我会将工具切换至后台然后打开浏览器，输入google，当页面加载很慢的时候，我将igniter切换至前台几秒马上再切换至浏览器前台，刚才未加载的页面将迅速加载出来，但是过一会，就又不行了。同样的trojan连接，在EMUI和Win上都很流畅的连接。我怀疑Harmony OS 2 可能对切换至后台的app进行了某些挂起操作导致的。期待您的修复。

刚才进行了日志添加，有如下提示：
```
You can't comment at this time — your comment is too long (maximum is 65536 characters).
```

**Comment by HaliComing** [comment]
不好意思，第一次issues中上传文件，刚看到下方有`  Attach files by dragging & dropping, selecting or pasting them.`。
[igniter-log.txt](https://github.com/trojan-gfw/igniter/files/6746271/igniter-log.txt)

**Comment by wongsyrone** [comment]
> cannot resolve remote server hostname example.io

看起来是无法解析域名了

**Comment by HaliComing** [comment]
我认为不是的，因为这个域名是我替换过的，`只去掉自己服务器的IP，密码等敏感信息即可`，我替换了自己的服务器IP。因为我的确能连接上并打开Google。这几天尝试了多次，发现切换至后台会导致这种问题，我开启了分屏模式，将igniter一直处于前台状态，同时打开浏览器，发现google等网站可以正常访问。当我将igniter切换至后台时，就出现了无法连接的情况。

**Comment by wongsyrone** [comment]
> 当我将igniter切换至后台时，就出现了无法连接的情况

你可能需要查一下怎么禁止鸿蒙做激进的内存优化

**Comment by HaliComing** [comment]
好的，期待您的修复。

**Comment by HaliComing** [comment]
感谢您今天的耐心解答

**Comment by TchaikovDriver** [comment]
这个问题描述看起来就是后台被杀引起的。adb获取logcat期间进程会被保活，但是平常使用的话会被系统杀掉。你只能查询鸿蒙系统后台白名单一类的做法，毕竟这是外部不可控因素。

HaliComing ***@***.***> 于 2021年7月1日周四 下午11:07写道：

**Comment by HaliComing** [comment]
是的，我认为你说的很正确，并且现在我的确也是这样做的，在系统设置中允许了它的后台活动


> 这个问题描述的好像是后台被杀的。 adb获取logcat在整个过程中会被保活，但是饮食使用杀掉的话会被系统系统删除
