### ISSUE TITLE
何时可以支持Trojan-go的相关功能？

### ISSUE THREAD

**Issue by keengrass** [trojan-gfw/igniter#388]
现在安卓平台上好像没有找到好用的trojan go 客户端

**Comment by Enter-ing** [comment]
支持下trojan-go吧，找了太多软件了，现在443一端就只能套cf，一套上就没有安卓的软件可以用了。。。

**Comment by wongsyrone** [comment]
https://github.com/p4gefau1t/trojan-go-android
