### ISSUE TITLE
not working on Android 12 beta 4

### ISSUE THREAD

**Issue by NewTX** [trojan-gfw/igniter#393]
on Android 12 beta 4 no internet connection after start proxy.

**Comment by EiChinn** [comment]
I also encountered the same problem, igniter can work on Android 8, Android 12 beta 3, but not on Android 12 beta 4

**Comment by iKirby** [comment]
It's a bug of Android 12 Beta 4. We have to wait for the next update.
https://issuetracker.google.com/issues/196271165

**Comment by tempersitu** [comment]
My pixel3 will lose function cuz I am in China mainland. I need VPN to connect Google. Now the VPN all don't work, I can't upgrade or downgrade to other version of OS T_T

**Comment by iKirby** [comment]
The VPN bug has been fixed via Google Play system update. Go to Settings -> Security -> Google Play system update to check for update. After installing the update and rebooting device, the Google Play system update version should be September 1, 2021.
