### ISSUE TITLE
miui13点击开始按钮无反应

### ISSUE THREAD

**Issue by Meaningisuse** [trojan-gfw/igniter#406]
系统：miui13
android版本： 12

描述：之前在miui12（android 11）是正常的，升级后无法使用，线刷重新安装系统后还是一样，ssr可正常使用，可排除是系统本身问题

**Comment by qiuyang57** [comment]
相同的问题，miui13无法启动

**Comment by pecliu** [comment]
Same problem. Cannot start in miui13

**Comment by pecliu** [comment]
I found that igniter 0.10.2-beta worked in MIUI 13.

but igniter 0.10.4-beta doesn't

**Comment by wongsyrone** [comment]
https://github.com/trojan-gfw/igniter/issues/399

**Comment by xiaoyvyv** [comment]
我打了一个最新修改的 apk，未做代码修改，可以在 Android12 上正常工作。
https://github.com/xiaoyvyv/igniter/releases/tag/v0.11

**Comment by tylearymf** [comment]
> 我打了一个最新修改的 apk，未做代码修改，可以在 （MIUI 13）Android12 上正常工作。 https://github.com/xiaoyvyv/igniter/releases/tag/v0.11

可以用，就是有时候会虽然显示是连接的，但是实际是断掉了，可能是哪里有报错了。

**Comment by Meaningisuse** [comment]
https://github.com/xxf098/shadowsocksr-v2ray-trojan-android
我现在用这客户端，大家可以试下，支持多种协议

**Comment by pecliu** [comment]
0.10.2-beta版本的apk可以在（MIUI 13）Android12 上运行

**Comment by liutf** [comment]
0.10.4-beta 在miui12.5 上的通知栏按钮也没了

**Comment by gongshoudao** [comment]
通知栏快捷开关的问题，把IgniterTileService改成android:exported="true"就可以了。

**Comment by syaoo** [comment]
iqoo Android12也是这个情况

**Comment by liutf** [comment]
> I found that igniter 0.10.2-beta worked in MIUI 13.
> 
> but igniter 0.10.4-beta doesn't

igniter-v0.10.3-beta-230001003-universal-release.apk worked in MIUI 13.0.4(Mi10)

**Comment by Jefsky** [comment]
我也有这个问题

**Comment by Jefsky** [comment]
> 我打了一个最新修改的 apk，未做代码修改，可以在 （MIUI 13）Android12 上正常工作。 https://github.com/xiaoyvyv/igniter/releases/tag/v0.11

感谢！可以用了

**Comment by Sayaka-4987** [comment]
Same on MIUI 14...
