### ISSUE TITLE
igniter固定端口号

### ISSUE THREAD

**Issue by liutf** [trojan-gfw/igniter#411]
igniter端口号现在都是随机的，每天使用Chrome SwitchyOmega 连接igniter，都要手动去填写一次端口号，太重复繁琐。

请问可以固定个端口号吗？或者有端口号有冲突的时候提示用户自己设置 或 再随机指定。重度用户求。

![image](https://user-images.githubusercontent.com/14069370/155863778-8342eade-6b67-461a-8eca-26ad25a16fe5.png)

**Comment by tylearymf** [comment]
> 

好奇问下，你这个不是win下的吗

**Comment by liutf** [comment]
> > 
> 
> 好奇问下，你这个不是win下的吗

是 Chrome 的 SwitchyOmega插件。跟操作系统没关系。

**Comment by tylearymf** [comment]
> > > 
> > 
> > 
> > 好奇问下，你这个不是win下的吗
> 
> 是 Chrome 的 SwitchyOmega插件。跟操作系统没关系。

这个是android下的呀

**Comment by liutf** [comment]
> > > > 
> > > 
> > > 
> > > 好奇问下，你这个不是win下的吗
> > 
> > 
> > 是 Chrome 的 SwitchyOmega插件。跟操作系统没关系。
> 
> 这个是android下的呀，你不是应该去trojan下问吗

![image](https://user-images.githubusercontent.com/14069370/155959114-0be21f1f-ece1-4677-bec1-f38a8764daa5.png)


    我是用SwitchyOmega访问igniter。

**Comment by TchaikovDriver** [comment]
#412

**Comment by TchaikovDriver** [comment]
#412 
等这个功能发布后就可以在设置里指定端口了。

**Comment by liutf** [comment]
> #412 等这个功能发布后就可以在设置里指定端口了。

好的，非常感谢与期待！

**Comment by tylearymf** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 好奇问下，你这个不是win下的吗
> > > 
> > > 
> > > 是 Chrome 的 SwitchyOmega插件。跟操作系统没关系。
> > 
> > 
> > 这个是android下的呀，你不是应该去trojan下问吗
> 
> ![image](https://user-images.githubusercontent.com/14069370/155959114-0be21f1f-ece1-4677-bec1-f38a8764daa5.png)
> 
> ```
> 我是用SwitchyOmega访问igniter。
> ```

学到了个新知识哈哈

**Comment by superbetacat** [comment]
请问一下题主，你是安卓上运行igniter然后在同一个局域网的PC上的chrome运行SwitchyOmega吗？
我也想这么用，但是我允许来自局域网的访问了，填写这个代理端口和手机的局域网IP，同一个局域网的PC上的chrome死活无法连接，，，可能有什么原因呢？
手机上已经能够正常上YouTube了，但是PC上的SwitchyOmega死活就是不work。。。

**Comment by tylearymf** [comment]
> 请问一下题主，你是安卓上运行igniter然后在同一个局域网的PC上的chrome运行SwitchyOmega吗？ 我也想这么用，但是我允许来自局域网的访问了，填写这个代理端口和手机的局域网IP，同一个局域网的PC上的chrome死活无法连接，，，可能有什么原因呢？ 手机上已经能够正常上YouTube了，但是PC上的SwitchyOmega死活就是不work。。。

SwitchyOmega上的地址要填跟路由器端同类地址，比如路由器的地址是192.168.50.1，那你SwitchyOmega上就要填192.168.xxx.xxx（手机的局域网地址），填172.xxx.xxx.xx我这边试了不行，虽然也能ping的通

**Comment by superbetacat** [comment]
> 

我确认已经填了局域网地址的，192.168.101.x
我用的是0.11.0-beta版本，能说下你用的哪个版本吗？
（忘记从哪儿下载的了，公开版的0.10.4-beta版在安卓12上有问题，点了连接没反应）

**Comment by superbetacat** [comment]
> > 请问一下题主，你是安卓上运行igniter然后在同一个局域网的PC上的chrome运行SwitchyOmega吗？ 我也想这么用，但是我允许来自局域网的访问了，填写这个代理端口和手机的局域网IP，同一个局域网的PC上的chrome死活无法连接，，，可能有什么原因呢？ 手机上已经能够正常上YouTube了，但是PC上的SwitchyOmega死活就是不work。。。
> 
> SwitchyOmega上的地址要填跟路由器端同类地址，比如路由器的地址是192.168.50.1，那你SwitchyOmega上就要填192.168.xxx.xxx（手机的局域网地址），填172.xxx.xxx.xx我这边试了不行，虽然也能ping的通
我确认已经填了局域网地址的，192.168.101.x
我用的是0.11.0-beta版本，能说下你用的哪个版本吗？
（忘记从哪儿下载的了，公开版的0.10.4-beta版在安卓12上有问题，点了连接没反应）

**Comment by tylearymf** [comment]
> > > 请问一下题主，你是安卓上运行igniter然后在同一个局域网的PC上的chrome运行SwitchyOmega吗？ 我也想这么用，但是我允许来自局域网的访问了，填写这个代理端口和手机的局域网IP，同一个局域网的PC上的chrome死活无法连接，，，可能有什么原因呢？ 手机上已经能够正常上YouTube了，但是PC上的SwitchyOmega死活就是不work。。。
> > 
> > 
> > SwitchyOmega上的地址要填跟路由器端同类地址，比如路由器的地址是192.168.50.1，那你SwitchyOmega上就要填192.168.xxx.xxx（手机的局域网地址），填172.xxx.xxx.xx我这边试了不行，虽然也能ping的通
> 
> 我确认已经填了局域网地址的，192.168.101.x 我用的是0.11.0-beta版本，能说下你用的哪个版本吗？ （忘记从哪儿下载的了，公开版的0.10.4-beta版在安卓12上有问题，点了连接没反应）

https://github.com/xiaoyvyv/igniter/releases/tag/v0.11
我是这里下载的，也是0.11.0-beta，安卓12环境，

**Comment by superbetacat** [comment]
> > > > 请问一下题主，你是安卓上运行igniter然后在同一个局域网的PC上的chrome运行SwitchyOmega吗？ 我也想这么用，但是我允许来自局域网的访问了，填写这个代理端口和手机的局域网IP，同一个局域网的PC上的chrome死活无法连接，，，可能有什么原因呢？ 手机上已经能够正常上YouTube了，但是PC上的SwitchyOmega死活就是不work。。。
> > > 
> > > 
> > > SwitchyOmega上的地址要填跟路由器端同类地址，比如路由器的地址是192.168.50.1，那你SwitchyOmega上就要填192.168.xxx.xxx（手机的局域网地址），填172.xxx.xxx.xx我这边试了不行，虽然也能ping的通
> > 
> > 
> > 我确认已经填了局域网地址的，192.168.101.x 我用的是0.11.0-beta版本，能说下你用的哪个版本吗？ （忘记从哪儿下载的了，公开版的0.10.4-beta版在安卓12上有问题，点了连接没反应）
> 
> https://github.com/xiaoyvyv/igniter/releases/tag/v0.11 我是这里下载的，也是0.11.0-beta，安卓12环境，


感谢，用这个确实可以了！！！

**Comment by liutf** [comment]
> > > > > 请问一下题主，你是安卓上运行igniter然后在同一个局域网的PC上的chrome运行SwitchyOmega吗？ 我也想这么用，但是我允许来自局域网的访问了，填写这个代理端口和手机的局域网IP，同一个局域网的PC上的chrome死活无法连接，，，可能有什么原因呢？ 手机上已经能够正常上YouTube了，但是PC上的SwitchyOmega死活就是不work。。。
> > > > 
> > > > 
> > > > SwitchyOmega上的地址要填跟路由器端同类地址，比如路由器的地址是192.168.50.1，那你SwitchyOmega上就要填192.168.xxx.xxx（手机的局域网地址），填172.xxx.xxx.xx我这边试了不行，虽然也能ping的通
> > > 
> > > 
> > > 我确认已经填了局域网地址的，192.168.101.x 我用的是0.11.0-beta版本，能说下你用的哪个版本吗？ （忘记从哪儿下载的了，公开版的0.10.4-beta版在安卓12上有问题，点了连接没反应）
> > 
> > 
> > https://github.com/xiaoyvyv/igniter/releases/tag/v0.11 我是这里下载的，也是0.11.0-beta，安卓12环境，
> 
> 感谢，用这个确实可以了！！！

  你们是使用换个安装包来解决的？  我之前貌似也是直接局域网连接是不行，然后使用姿势是： 手机打开热点，电脑连接手机的热点，就可以访问Google了。比较麻烦一点。

**Comment by superbetacat** [comment]
是的，下载这个包配合SwitchyOmega就可以了
分享热点那个应该是不行的

> > > > > > 请问一下题主，你是安卓上运行igniter然后在同一个局域网的PC上的chrome运行SwitchyOmega吗？ 我也想这么用，但是我允许来自局域网的访问了，填写这个代理端口和手机的局域网IP，同一个局域网的PC上的chrome死活无法连接，，，可能有什么原因呢？ 手机上已经能够正常上YouTube了，但是PC上的SwitchyOmega死活就是不work。。。
> > > > > 
> > > > > 
> > > > > SwitchyOmega上的地址要填跟路由器端同类地址，比如路由器的地址是192.168.50.1，那你SwitchyOmega上就要填192.168.xxx.xxx（手机的局域网地址），填172.xxx.xxx.xx我这边试了不行，虽然也能ping的通
> > > > 
> > > > 
> > > > 我确认已经填了局域网地址的，192.168.101.x 我用的是0.11.0-beta版本，能说下你用的哪个版本吗？ （忘记从哪儿下载的了，公开版的0.10.4-beta版在安卓12上有问题，点了连接没反应）
> > > 
> > > 
> > > https://github.com/xiaoyvyv/igniter/releases/tag/v0.11 我是这里下载的，也是0.11.0-beta，安卓12环境，
> > 
> > 
> > 感谢，用这个确实可以了！！！
> 
> 你们是使用换个安装包来解决的？ 我之前貌似也是直接局域网连接是不行，然后使用姿势是： 手机打开热点，电脑连接手机的热点，就可以访问Google了。比较麻烦一点。

**Comment by calidion** [comment]
@liutf 

https://github.com/low-api-support-trojan/igniter/releases/tag/las-v0.2.0

版本 0.2.0 已经支持你的需求。

**Comment by liutf** [comment]
感谢大佬！

**Comment by liutf** [comment]
> @liutf
> 
> https://github.com/low-api-support-trojan/igniter/releases/tag/las-v0.2.0
> 
> 版本 0.2.0 已经支持你的需求。

感谢大佬！

**Comment by calidion** [comment]
欢迎试用，代码尚不稳定，欢迎反馈。
