### ISSUE TITLE
[help wanted] Cannot build this project

### ISSUE THREAD

**Issue by superbetacat** [trojan-gfw/igniter#415]
想在本地build 这个项目，但是经过几天的尝试，仍然失败。
有没有成功build 的，告诉我一下我的步骤哪里有问题？

环境： Ubuntu 2004 LTS
Android studio：最新版2021

我尝试的步骤如下：
一：build server
1. git clone trojan 到本地；
2. 安装必要依赖库，apt-get install libboost-all-dev default-libmysqlclient-dev libssl-dev 等
3. 执行 cd trojan/ && cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DSYSTEMD_SERVICE=ON . 
4. build成功。

二：build client
1. git clone igniter；
2. 下载最新版 golib.aar到app/src/libs；
3. 从trojan里把cpp里的源文件copy到~/igniter/app/src/main/cpp/trojan:  cp -r ~/trojan/src/   ~/igniter/app/src/main/cpp/trojan
6. 删除main.cpp。
7. 从github上搜到以下几个库放在~/igniter/app/src/main/cpp/libs/lib/arm64-v8a。 （这一步有问题？）
-rw-rw-r-- 1 ubuntu ubuntu 1626164 May  8 15:16 libboost_program_options.a
-rw-rw-r-- 1 ubuntu ubuntu    1444 May  8 15:16 libboost_system.a
-rw-rw-r-- 1 ubuntu ubuntu 7522818 May  8 15:16 libcrypto.a
-rw-rw-r-- 1 ubuntu ubuntu  955222 May  8 15:16 libssl.a
8. 在Android studio里点build apk。

然后就提示找不到一些boost的文件错误：
In file included from /home/ubuntu/igniter/app/src/main/cpp/trojan/src/core/authenticator.cpp:20:
In file included from /home/ubuntu/igniter/app/src/main/cpp/trojan/src/core/authenticator.h:26:
/home/ubuntu/igniter/app/src/main/cpp/trojan/src/core/config.h:25:10: fatal error: 'boost/property_tree/ptree.hpp' file not found

In file included from /home/ubuntu/igniter/app/src/main/cpp/jni-helper.cpp:5:
/home/ubuntu/igniter/app/src/main/cpp/trojan/src/core/config.h:25:10: fatal error: 'boost/property_tree/ptree.hpp' file not found

In file included from /home/ubuntu/igniter/app/src/main/cpp/trojan/src/core/log.cpp:20:
/home/ubuntu/igniter/app/src/main/cpp/trojan/src/core/log.h:25:10: fatal error: 'boost/asio/ip/tcp.hpp' file not found

但是这些头文件其实是存在的，因为第一步build trojan  server是成功了的，而且这些文件也确实存在：
ubuntu@ip-172-26-8-5:/usr/include/boost$ ls -la property_tree/ptree.hpp   asio/ip/tcp.hpp
-rw-r--r-- 1 root root  3808 Apr  1  2020 asio/ip/tcp.hpp
-rw-r--r-- 1 root root 20867 Apr  1  2020 property_tree/ptree.hpp

有没有大佬指示一下，我哪里做错了，正确应该怎么做呢？
步骤7里的几个文件我应该从哪里获取才是正确的？
感谢！

**Comment by wongsyrone** [comment]
https://github.com/trojan-gfw/igniter/blob/master/.circleci/config.yml
