### ISSUE TITLE
不知道怎么导入证书到手机

### ISSUE THREAD

**Issue by heham** [trojan-gfw/igniter#43]
服务端已经部署好了，电脑上可以成功了，客户端文件夹内有个fullchain.cer证书，但是需要私约才能安装到手机，部署的时候是用的一键脚本没有看到私钥

**Comment by chchia** [comment]
不需要，直接输入config.json里的password

**Comment by heham** [comment]
> 不需要，直接输入config.json里的password

那个都抄过来了就是不行的

**Comment by heham** [comment]
删了重新安装似乎好了，但是与安卓10系统可能有点问题

**Comment by 6k1993** [comment]
导入证书方式如下:
将证书文件复制进安卓手机,安卓文件管理器里点击证书文件,导入系统就行了
