### ISSUE TITLE
It's will disconnect

### ISSUE THREAD

**Issue by ALTHRIVEO** [trojan-gfw/igniter#44]
Sometimes I start vpn,but about 30 second later, I can't open the google and other web,but it's always displayed it's connecting,no data transfer.

**Comment by GreaterFire** [comment]
Unable to debug this due to insufficient information provided.

**Comment by sexfio** [comment]
我也遇到过。。。。。

**Comment by ALTHRIVEO** [comment]
whats ur mobile,mine is samsung s9 plus

**Comment by antoniacrespoa2** [comment]
If any Android skins are being used, OneUI, MIUI, etc, add Igniter to background process whitelist. If on stock-like Android, try disabling battery optimization for Igniter.

**Comment by ALTHRIVEO** [comment]
it's seems working well after i installed the alpha 12 version,i didn't do any setting just install the new version.

**Comment by wongsyrone** [comment]
Closing due to the original author solved the issue by installing the latest version.
