### ISSUE TITLE
Doesn't reconnect from Network settings

### ISSUE THREAD

**Issue by klzgrad** [trojan-gfw/igniter#5]
After VPN is disconnected, it won't start from Network & internet > Advanced > VPN > Igniter > Connect.

**Comment by SakuraSa233** [comment]
Are you sure it is not a bug of your oprate system? There shouldn't be a "connnect" for VPN established by app.

**Comment by GreaterFire** [comment]
True. For VPN connections established by an app, it can only be initiated in the app.

**Comment by klzgrad** [comment]
Ok, I was confused with the first one. Will check how to repro it later.

Here's another set of steps to trigger a similar behavior:
1. Start the vpn from within the app
2. Disconnect the vpn from network settings in a location similar to above (a prompt asking Cancel or Disconnect)
3. Start the vpn from the app

Result: network timeout

If I replace step 2 with stopping the vpn from within the app it works normally.

**Comment by oasiscifr** [comment]
fixed in https://github.com/trojan-gfw/igniter/pull/36
