### ISSUE TITLE
关于使用WIFI连接就基本特别慢且一点都不稳定的问题

### ISSUE THREAD

**Issue by XFGRASS** [trojan-gfw/igniter#57]
介于这里使用的大部分应该都是中国人就用中文说下我最近的发现

**Comment by XFGRASS** [comment]
1.首先我的WIFI和PC网线是同一个路由器的，我的PC端没有任何问题
2.然后我发现只要我手机上断开WIFI连接，再重新连接，然后再打开ingiter，那么此时会持续大约十多次左右的请求没有任何问题（我用youtube下拉刷新首页来测试的)，但是过了十多次之后，速度又会变得特别慢且不稳定，然后再断开WIFI再重新连就又是这样

**Comment by XFGRASS** [comment]
所以有没有懂哥能分析一下这个问题，为什么WIFI重连后的几十次请求就没问题，几十次之后就又变慢，是不是几十次之后，有什么其他原因对数据进行了堵塞，我在路由器上已经关闭了防火墙还是一样

**Comment by wongsyrone** [comment]
使用的哪个版本，提供logcat，如有必要，提供屏幕录屏

**Comment by XFGRASS** [comment]
> 使用的哪个版本，提供logcat，如有必要，提供屏幕录屏

感谢回复，已经解决了啊，2333，说起来原因有点搞笑，我logcat了半天都没发现什么有用的信息，然后我突然觉得会不会是手机WIFI本身的原因，于是我就去看了一下WIFI设置，因为我用的小米，然后他有一个网速模式设置，他默认给我开启了极致模式，也就是当前应用优先享用网络资源，但会抢占后台其他应用的网络资源使用，这才反应过来是怎么回事，然后把这个关了就ok了

**Comment by llcat** [comment]
> > 使用的哪个版本，提供logcat，如有必要，提供屏幕录屏
> 
> 感谢回复，已经解决了啊，2333，说起来原因有点搞笑，我logcat了半天都没发现什么有用的信息，然后我突然觉得会不会是手机WIFI本身的原因，于是我就去看了一下WIFI设置，因为我用的小米，然后他有一个网速模式设置，他默认给我开启了极致模式，也就是当前应用优先享用网络资源，但会抢占后台其他应用的网络资源使用，这才反应过来是怎么回事，然后把这个关了就ok了

👍 被折腾了十几天，没想到是这个原因，佛了

**Comment by oasiscifr** [comment]
@llcat 🙃
