### ISSUE TITLE
Add a quick switch Tile

### ISSUE THREAD

**Issue by b862** [trojan-gfw/igniter#59]
just like shadowsocks...it will be more convenient 
![Screenshot_20200123-103612_One UI Home](https://user-images.githubusercontent.com/18390127/72952295-5b251100-3dcc-11ea-9188-57f723bbc630.jpg)

**Comment by txdywy** [comment]
agree

CEOX <notifications@github.com> 于 2020年1月23日周四 上午10:37写道：

**Comment by becomedoc** [comment]
cant agree more. one step from perfect

**Comment by mofada** [comment]
Good advice

**Comment by VictorAlexanderMa** [comment]
Excellent, this is just the function I need~

**Comment by luoxiao-xy** [comment]
非常需要这个功能！

**Comment by oldthreefeng** [comment]
cant agree more.

**Comment by TchaikovDriver** [comment]
I will do that when I am spare.

**Comment by TchaikovDriver** [comment]
> I will do that when I am spare.

#142

**Comment by wongsyrone** [comment]
Added via https://github.com/trojan-gfw/igniter/pull/142
