### ISSUE TITLE
'Verify Certificate' option is offered but nowhere to choose the certificate file from

### ISSUE THREAD

**Issue by ldwnt** [trojan-gfw/igniter#62]
How can I specify the certificate file, as offered in the linux client?
```
    "ssl": {
        "verify": true,
        "verify_hostname": true,
        "cert": "xxx",
```

**Comment by ldwnt** [comment]
@oasiscifr any plan to add this feature? is it dangerous with Verify Certificate = false ?

**Comment by oasiscifr** [comment]
@ldwnt This feature would be only useful for trojan server with self signed certificate. If you followed the official doc and employed legal certificates, you don't need to provide any extra cert files here to enable Verify Certificate.

**Comment by wongsyrone** [comment]
You can import self-signed certificates follow the instructions provided here: https://github.com/trojan-gfw/igniter/issues/43#issuecomment-572439214

**Comment by GreaterFire** [comment]
@ldwnt The option will verify against Mozilla's CA extract. Yes, turn this off is insecure.

**Comment by ldwnt** [comment]
> @ldwnt The option will verify against Mozilla's CA extract. Yes, turning this off is insecure.

You mean it's insecure for self-singed certificates with this option set to off? @oasiscifr claims the verification is not needed for legal certificates.

**Comment by wongsyrone** [comment]
> verification is not needed for legal certificates.

You misunderstood his meaning. Legal certificates will be verified via the embedded CA certs, if you do use self-signed certs, which is strongly discouraged, you have to import the self-signed cert to the Android system.

**Comment by wongsyrone** [comment]
I plan to ignore the feature request to choose the certification file, it encourages users to use self-signed certificates and hurts the overall environment. Users must do the manual intervention to make it work, with full acknowledgment of security vulnerability.
