### ISSUE TITLE
UI refining needed

### ISSUE THREAD

**Issue by oasiscifr** [trojan-gfw/igniter#69]
There are two more controls on the main UI now.

**Comment by oasiscifr** [comment]
@Alexinst
I know less about Android UI. Can you help us to refine it?

**Comment by Alexinst** [comment]
@oasiscifr Could you explain the task more clearly?

**Comment by oasiscifr** [comment]
@Alexinst Two features are added recently, introducing a sharelink  textEdit and test connection button. At least on my device, they exceed the screen. I think we'd better refine the UI before make a new release.

**Comment by Alexinst** [comment]
@oasiscifr I would take a try.

**Comment by Alexinst** [comment]
@oasiscifr How is this? 
![Snipaste_2020-02-06_21-39-42](https://user-images.githubusercontent.com/23702319/73942173-94f82a80-4929-11ea-8db3-6cc9d40ca2f0.png)
![Snipaste_2020-02-06_21-39-23](https://user-images.githubusercontent.com/23702319/73942184-99bcde80-4929-11ea-9b38-78bbb7a87f39.png)

**Comment by oasiscifr** [comment]
@Alexinst Looks far more better!

**Comment by Alexinst** [comment]
@oasiscifr I have created a new PR(#70).

**Comment by Alexinst** [comment]
@oasiscifr Here is the new PR(#71).

**Comment by GreaterFire** [comment]
@Alexinst Please directly commit to your branch if you have new changes. Don't open a new pull request.

**Comment by Alexinst** [comment]
@Alexinst I have committed to my branch before opening a new pull request. And if I don't open a new PR, how do I commit the changes? XD

**Comment by GreaterFire** [comment]
@Alexinst Your changes to your original branch will show up in the pull request. This is just how it works.

**Comment by Alexinst** [comment]
@GreaterFire Sorry, I'm confused now. Should I close the PR(#71)?

**Comment by GreaterFire** [comment]
@Alexinst Nah. You have opened it just keep it open. Be mindful next time.

**Comment by Alexinst** [comment]
@GreaterFire I commit and push my code to my fork repo(alexinst/igniter), and open a new PR to this repo(trojan-gfw/igniter). What's wrong with it, anything that should't be done? XD

**Comment by GreaterFire** [comment]
@Alexinst I'm interested in why you opened #70 and then closed it and opened #71.

**Comment by Alexinst** [comment]
Something new was just committed by wongsyrone. I didn't notice it before I open #70. So, I close #70 and run 'git rebase'. XD

**Comment by GreaterFire** [comment]
@Alexinst What you should do is, you should rebase your change to master and force push to your branch.

**Comment by GreaterFire** [comment]
@Alexinst [In reply to GreaterFire 大火酱]
Also, it doesn't really matter if master is newer than you. If you made unrelated changes then the 3-way merger will handle the situation gracefully.

**Comment by Alexinst** [comment]
@GreaterFire OK, I see. Thank you!
