### ISSUE TITLE
4g用不了，wifi倒是可以用？

### ISSUE THREAD

**Issue by w972314191** [trojan-gfw/igniter#72]
电脑端的没问题，4g给电脑开热点也可以科学上网。手机使用wifi也没问题，但是4g网络使用igniter在手机端就是连不上外网。

**Comment by txdywy** [comment]
运营商干掉了

**Comment by txdywy** [comment]
可能dns有问题

**Comment by ncnylon** [comment]
@w972314191 你是用什麼版本的啊？我用**0.1.0-pre-alpha13**不能上網，用**0.1.0-pre-alpha12**的就可以了，你也可以試試看。

**Comment by w972314191** [comment]
> 可能dns有问题

在服务器端设置一下dns是吗？

**Comment by w972314191** [comment]
@ncnylon 感谢老哥，但是没用。。。

**Comment by w972314191** [comment]
> 可能dns有问题

可能不是，因为电脑连接手机热点然后用v2rayN trojan版依旧可以成功上外网

**Comment by hurui** [comment]
我遇到和你一样的问题，已经解决了，具体原因是，移动网用的ipv6。具体的解决办法有两个：

1. 关闭移动网络的ipv6，只使用ipv4，具体的方法你可以用 Google 搜索 Android apn 配置 ipv4
2. 首先获取服务器的ipv6地址，添加dns aaaa记录，然后在 trojan 服务端配置 "local_addr": "0.0.0.0"改为"local_addr": "::"

**Comment by Lantrancy** [comment]
额，开关一下app就行了，切换网络他不会自动重连。。。。

**Comment by cmlzgc** [comment]
我的情况正好相反，打开4G可以用，打开WIFI就不行，弄的我流量都不够了。有没有大佬帮我解救下？

**Comment by onyourhead** [comment]
我也是，4g连接后test connection显示ssl握手失败，但是连上wifi就没问题

**Comment by Elusive0079** [comment]
我的问题很奇怪，在同一wifi环境下，一台手机能用，另一台不能。不能用的那一台是荣耀的20pro，magic3.0安卓10，然而另一台手机是同样的系统，不同手机型号，可以正常使用。这台不能使用的手机就算重置全部设置还是没有用。测试链接报错connection closed by peer，有没有大佬能救救我

**Comment by wongsyrone** [comment]
你们这些人我真的服了，都说不能用，一个发logcat的都没有，我是神仙吗？

**Comment by wongsyrone** [comment]
Close due to no enough information to determine the root cause.
