### ISSUE TITLE
How to use "by pass China with clash" ?

### ISSUE THREAD

**Issue by TheAutomatic** [trojan-gfw/igniter#74]
I've downloaded clash for Android in my phone. But I don't know if there's any connection between these two apps.
Should I open both of them to make the bypass functional? And what should set in clash?
Thanks.

**Comment by TheAutomatic** [comment]
To make myself clear. 
These two apps infers to "clash for Android" and "Igniter".

**Comment by GreaterFire** [comment]
@TheAutomatic No. Igniter includes a copy of clash. You don't have to do anything extra to use the functionality.
