### ISSUE TITLE
profile list

### ISSUE THREAD

**Issue by dagai233** [trojan-gfw/igniter#77]
I hope to increase the node list. Now only one node can be added. I hope that the function of saving multiple nodes can be added later. Like v2rayNy, thank you very much!

**Comment by wongsyrone** [comment]
For me, it's a low-priority task.

**Comment by luoxiao-xy** [comment]
确实很需要这个功能！对于用户来说这个很重要。因为不能确保一个代理在此时此刻是可以用的。多个代理可以在不可用时切换！

**Comment by TchaikovDriver** [comment]
> For me, it's a low-priority task.

I've created a pull request which contains this feature.

**Comment by oasiscifr** [comment]
@TchaikovDriver I saw. We will review it when we have time. [beer]

**Comment by wongsyrone** [comment]
Added via https://github.com/trojan-gfw/igniter/pull/101
