### ISSUE TITLE
android 6.0 can't install

### ISSUE THREAD

**Issue by lihaixin** [trojan-gfw/igniter#8]
I use xiaomi redmi note3 and xiaomi mi note can't install this app,the two android os version is android 6.01

**Comment by GreaterFire** [comment]
@lihaixin Please provide a screenshot.

**Comment by wongsyrone** [comment]
@lihaixin and logcat please

**Comment by lihaixin** [comment]
![screenshot_2019-02-13-15-45-18-621_com miui packageinstaller](https://user-images.githubusercontent.com/1014736/52695091-8e4d0680-2fa6-11e9-969e-8da47bcc13d0.png)
![screenshot_2019-02-13-15-45-22-261_com miui packageinstaller](https://user-images.githubusercontent.com/1014736/52695102-9442e780-2fa6-11e9-8ec6-789f9bec3df8.png)

**Comment by lihaixin** [comment]
how to get logcat ?

**Comment by GreaterFire** [comment]
@lihaixin Is it app-debug.apk or app-release.apk?

**Comment by llll1987llll** [comment]
The same problem occur on my phone LG g5 with Android 6.0.1, both the debug and release apk of alpha 7.

**Comment by wongsyrone** [comment]
https://stackoverflow.com/questions/33149140/play-store-cant-install-app-error-code-103

Did you select V1 and V2 sig when building the app?

You may try https://drive.google.com/open?id=13EkClXuV7Dg4liax1Lbu7R_r718EvqQf to see if it's the case.

**Comment by lihaixin** [comment]
thanks! I use  this link app https://drive.google.com/open?id=13EkClXuV7Dg4liax1Lbu7R_r718EvqQf  success install the android 6.0 os

**Comment by llll1987llll** [comment]
So sad, can not even install the app above downloaded  from Googledrive by my phone with 6.0.1

**Comment by llll1987llll** [comment]
I uninstall the old version igniter app installed in my 6.0.1 os phone , then I can install the app downloaded from Google drive , but none of the aphla 7 app both the debug and release . The installed app downloaded from Google drive run successfully.

**Comment by wongsyrone** [comment]
Forgot to mention you have to uninstall the old one, due to different signing keystore.

**Comment by siaimes** [comment]
A few days ago, I encountered an installation package parsing failure. The reason is that I downloaded the igniter installation package from GitHub using the Thunder network, but the Thunder network download is not an installation package, just the same name. Later, I downloaded the installation package with the chrome built-in downloader and installed it.

**Comment by GreaterFire** [comment]
@siaimes Did you still have the problem or you are just stating the cause of the problem?

**Comment by siaimes** [comment]
@GreaterFire Just a statement of the problem I encountered in order to give @llll1987llll  a reference.
