### ISSUE TITLE
test connection error

### ISSUE THREAD

**Issue by A0620-00** [trojan-gfw/igniter#80]
Igniter:Failed to connect to https://www.google.com:Attempt to read from filed 'long io.github.trojan_gfw.igniter.ProxyService.tun2socksPort' on a null object reference

**Comment by wongsyrone** [comment]
Should be fixed via https://github.com/trojan-gfw/igniter/commit/10ea5ea21dbcfae3dc35ee5d0960c6faa6a1935a
