### ISSUE TITLE
希望可以添加分应用代理的功能

### ISSUE THREAD

**Issue by my1933** [trojan-gfw/igniter#83]
希望可以添加分应用代理的功能，因为有时候没有分应用代理的功能的话非常不方便。

**Comment by wongsyrone** [comment]
Duplicate of #4

**Comment by VictorAlexanderMa** [comment]
我也正是想提出这个问题，发现你和其他人已经提出了。分应用代理确实是非常有必要的功能，希望后期能够加入。

**Comment by GreaterFire** [comment]
@VictorAlexanderMa Please. It's better if you contribute than asking again and again and again.
