### ISSUE TITLE
try to build the project, but error occured

### ISSUE THREAD

**Issue by jados** [trojan-gfw/igniter#84]
![Snipaste_2020-02-18_09-49-17](https://user-images.githubusercontent.com/1528012/74697007-638a3380-5234-11ea-9b7e-99e953486b54.png)

**Comment by wongsyrone** [comment]
`dep ensure -update`

**Comment by jados** [comment]
@wongsyrone it didn't work.
![image](https://user-images.githubusercontent.com/1528012/74705163-e23f9a80-524d-11ea-8b84-5af98f2d2ee4.png)

**Comment by wongsyrone** [comment]
Read the `dep` doc and set it up properly.

ref:
https://golang.github.io/dep/
