### ISSUE TITLE
能否为密码和URL添加显示开关?

### ISSUE THREAD

**Issue by philosopher233** [trojan-gfw/igniter#85]
Trojan URL中含有密码, 那上面密码显示为••••••岂不是没有意义? 感谢!

**Comment by philosopher233** [comment]
或者做个类似于显示密码的开关?

**Comment by philosopher233** [comment]
大概长这样, 图片是瞎p的
![demo](https://user-images.githubusercontent.com/39409532/74734923-8e06db80-528a-11ea-9be6-8bbc40cf7911.png)

**Comment by wongsyrone** [comment]
It will show content on focus and get masked when losing focus.

Ref:
https://github.com/trojan-gfw/igniter/commit/8e1907140711309cc1c43ae8d2863117d09ab10d
https://github.com/trojan-gfw/igniter/commit/65eee29f3cf4dd51cc20a0ad295b38acdc2627d2

**Comment by philosopher233** [comment]
> It will show content on focus and get masked when losing focus.
> 
> Ref:
> [8e19071](https://github.com/trojan-gfw/igniter/commit/8e1907140711309cc1c43ae8d2863117d09ab10d)
> [65eee29](https://github.com/trojan-gfw/igniter/commit/65eee29f3cf4dd51cc20a0ad295b38acdc2627d2)

Thank you! 感谢!
