### ISSUE TITLE
Application control

### ISSUE THREAD

**Issue by mofada** [trojan-gfw/igniter#86]
Can I add an application control? For example, for some applications I do not need a proxy, I can manually set it to not proxy.

**Comment by KunagisaYuki** [comment]
@mofada This is already on schedule and partially finished. However currently we don't have a fixed day for the feature's implement.

**Comment by mofada** [comment]
Okay thank you

**Comment by oasiscifr** [comment]
https://github.com/trojan-gfw/igniter/issues/4
