### ISSUE TITLE
This app cant take effect on Honor 20pro

### ISSUE THREAD

**Issue by Elusive0079** [trojan-gfw/igniter#88]
I think i input my domain name and passwd correctly。 But after the vpn network established，i can't bypass GFW. If i close "Bypass China with Clash", I cant visit any website.
The system is Magic 3.0.0  10.0.0.190(C00E62R4P11patch01), and igniter works on another Huaweiphone whose system is 10.0.0.189.

**Comment by wongsyrone** [comment]
Close due to no enough information to determine the root cause.
