### ISSUE TITLE
My android6.0.1 phone cannot run this app

### ISSUE THREAD

**Issue by fuzhengqu** [trojan-gfw/igniter#89]
I use the Samsung note4 phone, exynos version, samsung official android6.0.1 . After installing igniter, I can enter information when  open it for the first time, but click to run it will stop working. If I open it again, it will always appear stop working.At present my trojan server has been build, but it cannot be run on mobile phones。

**Comment by wongsyrone** [comment]
Close due to no enough information to determine the root cause.

**Comment by fuzhengqu** [comment]
So why does the first version can work?

**Comment by GreaterFire** [comment]
Please reply with useful information.
