### ISSUE TITLE
Update geoip by users

### ISSUE THREAD

**Issue by wordlesswind** [trojan-gfw/igniter#90]
I think this is a basic function to ensure the good operation of the "Bypass China" function.

And after **December 30, 2019**, MaxMind requiring users of MaxMind GeoLite2 databases **to [register for a MaxMind account](https://www.maxmind.com/en/geolite2/signup)  and obtain a license key in order to download GeoLite2 databases**. [Learn more on MaxMind blog](https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/).

Examples of Permalinks: https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=YOUR_LICENSE_KEY&suffix=tar.gz
> You will need to replace the `YOUR_LICENSE_KEY` placeholder with an active license key associated **with your MaxMind account.**
You can see **your license key information on [your account License Keys page](https://www.maxmind.com/en/accounts/current/license-key)**.

**Comment by wongsyrone** [comment]
No plan for that.
