### ISSUE TITLE
Please add this application to Google play.

### ISSUE THREAD

**Issue by ALTHRIVEO** [trojan-gfw/igniter#91]
Forgive my laziness，Google play store is easier than GitHub to find the release.🙉

**Comment by wongsyrone** [comment]
It requires a $25 registration fee to publish apps to Google Play.

**Comment by ALTHRIVEO** [comment]
lol,i see,thanks

**Comment by ALTHRIVEO** [comment]
Will you add subscriptions in the future?

**Comment by wongsyrone** [comment]
Unless there is any official spec.
