### ISSUE TITLE
can i use it on android box?

### ISSUE THREAD

**Issue by johnsterkong** [trojan-gfw/igniter#94]
i try it on android tv, but it can't work.

**Comment by oasiscifr** [comment]
Support only Android 5 and above FYI.

**Comment by wongsyrone** [comment]
Might caused by missing corresponding layout definitions. I don't have Android TV, cannot develop neither debugging.

**Comment by wongsyrone** [comment]
We do NOT support MIPS thus cannot work on such platform. Please check your box architecture.
